/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const AccountableCreateDetails = zod
	.strictObject({
		tax_treatment: zod.enum(["taxable", "tax_deferred", "tax_exempt"]).exactOptional(),
		year_built: zod.int().exactOptional(),
		area_unit: zod.string().exactOptional(),
		area_value: zod.int().exactOptional(),
		make: zod.string().exactOptional(),
		model: zod.string().exactOptional(),
		year: zod.int().exactOptional(),
		mileage_value: zod.int().exactOptional(),
		mileage_unit: zod.string().exactOptional(),
		available_credit: zod.number().exactOptional(),
		minimum_payment: zod.number().exactOptional(),
		apr: zod.number().exactOptional(),
		annual_fee: zod.number().exactOptional(),
		expiration_date: zod.iso.date().exactOptional(),
		rate_type: zod.string().exactOptional(),
		interest_rate: zod.number().exactOptional(),
		term_months: zod.int().exactOptional(),
		initial_balance: zod.number().exactOptional(),
		address: zod
			.strictObject({
				line1: zod.string().exactOptional(),
				line2: zod.string().exactOptional(),
				locality: zod.string().exactOptional(),
				region: zod.string().exactOptional(),
				country: zod.string().exactOptional(),
				postal_code: zod.string().exactOptional(),
				county: zod.string().exactOptional(),
			})
			.exactOptional(),
	})
	.describe(
		"Type-specific manual account fields. Fields that do not apply to account_type are ignored.",
	);

export type AccountableCreateDetails = zod.input<typeof AccountableCreateDetails>;
export type AccountableCreateDetailsOutput = zod.output<typeof AccountableCreateDetails>;
