/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const AccountUpdateRequest = zod.strictObject({
	account: zod
		.strictObject({
			name: zod.string().exactOptional().describe("Account display name"),
			balance: zod
				.number()
				.exactOptional()
				.describe("Current balance in major currency units; writes a manual valuation entry"),
			currency: zod.string().exactOptional().describe("ISO currency code"),
			subtype: zod.string().nullish().describe("Account subtype for the existing account type"),
			institution_name: zod.string().nullish(),
			notes: zod.string().nullish(),
		})
		.describe(
			"Core manual account fields. Provider unlinking, sharing/ownership, report/default settings, and advanced subtype metadata are not part of the core milestone.",
		),
});

export type AccountUpdateRequest = zod.input<typeof AccountUpdateRequest>;
export type AccountUpdateRequestOutput = zod.output<typeof AccountUpdateRequest>;
