/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const Account = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "account_type": zod.string().nullable(),
  "status": zod.string().optional()
});

export type Account = zod.input<typeof Account>;
export type AccountOutput = zod.output<typeof Account>;
