/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const AccountDetail = zod.strictObject({
	id: zod.uuid(),
	name: zod.string(),
	balance: zod.string(),
	balance_cents: zod.int().describe("Signed balance in minor currency units"),
	cash_balance: zod.string(),
	cash_balance_cents: zod.int().describe("Signed cash balance in minor currency units"),
	currency: zod.string(),
	classification: zod.string(),
	account_type: zod.string().nullable(),
	subtype: zod.string().nullish(),
	status: zod.enum(["active", "draft", "disabled", "pending_deletion"]),
	institution_name: zod.string().nullish(),
	institution_domain: zod.string().nullish(),
	manual: zod
		.boolean()
		.exactOptional()
		.describe("True when the account has no live sync provider attached"),
	linked: zod
		.boolean()
		.exactOptional()
		.describe("True when the account is linked to a sync provider"),
	capabilities: zod
		.array(zod.enum(["read", "update", "archive", "delete"]))
		.exactOptional()
		.describe("Core actions the caller may attempt on this account"),
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
});

export type AccountDetail = zod.input<typeof AccountDetail>;
export type AccountDetailOutput = zod.output<typeof AccountDetail>;
