/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const AccountableCreateDetails = zod.object({
  "tax_treatment": zod.enum(['taxable', 'tax_deferred', 'tax_exempt']).optional(),
  "year_built": zod.int().optional(),
  "area_unit": zod.string().optional(),
  "area_value": zod.int().optional(),
  "make": zod.string().optional(),
  "model": zod.string().optional(),
  "year": zod.int().optional(),
  "mileage_value": zod.int().optional(),
  "mileage_unit": zod.string().optional(),
  "available_credit": zod.number().optional(),
  "minimum_payment": zod.number().optional(),
  "apr": zod.number().optional(),
  "annual_fee": zod.number().optional(),
  "expiration_date": zod.iso.date().optional(),
  "rate_type": zod.string().optional(),
  "interest_rate": zod.number().optional(),
  "term_months": zod.int().optional(),
  "initial_balance": zod.number().optional(),
  "address": zod.object({
  "line1": zod.string().optional(),
  "line2": zod.string().optional(),
  "locality": zod.string().optional(),
  "region": zod.string().optional(),
  "country": zod.string().optional(),
  "postal_code": zod.string().optional(),
  "county": zod.string().optional()
}).optional()
}).describe('Type-specific manual account fields. Fields that do not apply to account_type are ignored.');

export type AccountableCreateDetails = zod.input<typeof AccountableCreateDetails>;
export type AccountableCreateDetailsOutput = zod.output<typeof AccountableCreateDetails>;
