/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ApiMetadata = zod.strictObject({
	api_version: zod
		.string()
		.describe(
			"Semver contract version served by this Rails build. The alternate frontend supports major version 1.",
		),
	capabilities: zod
		.array(zod.string())
		.describe(
			"Capability tokens the alternate frontend requires for session establishment. Removing or renaming one is a breaking change.",
		),
});

export type ApiMetadata = zod.input<typeof ApiMetadata>;
export type ApiMetadataOutput = zod.output<typeof ApiMetadata>;
