/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const BalanceAccount = zod.strictObject({
	id: zod.uuid(),
	name: zod.string(),
	account_type: zod.string().nullable(),
});

export type BalanceAccount = zod.input<typeof BalanceAccount>;
export type BalanceAccountOutput = zod.output<typeof BalanceAccount>;
