/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { Money } from './money.zod.ts';

export const BalanceSheet = zod.object({
  "currency": zod.string().describe('Family primary currency'),
  "net_worth": Money,
  "assets": Money,
  "liabilities": Money
});

export type BalanceSheet = zod.input<typeof BalanceSheet>;
export type BalanceSheetOutput = zod.output<typeof BalanceSheet>;
