/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const BudgetCategory = zod.object({
  "id": zod.uuid(),
  "budget_id": zod.uuid(),
  "currency": zod.string(),
  "subcategory": zod.boolean(),
  "inherits_parent_budget": zod.boolean(),
  "rollover_enabled": zod.boolean(),
  "budgeted_spending": zod.string().optional(),
  "budgeted_spending_cents": zod.int().optional(),
  "display_budgeted_spending": zod.string().optional(),
  "display_budgeted_spending_cents": zod.int().optional(),
  "actual_spending": zod.string().optional(),
  "actual_spending_cents": zod.int().optional(),
  "rolled_over_amount": zod.string().optional(),
  "rolled_over_amount_cents": zod.int().optional(),
  "available_to_spend": zod.string().optional(),
  "available_to_spend_cents": zod.int().optional(),
  "category": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "color": zod.string(),
  "lucide_icon": zod.string(),
  "parent_id": zod.uuid().nullish()
}),
  "created_at": zod.iso.datetime({"offset":true}),
  "updated_at": zod.iso.datetime({"offset":true})
});

export type BudgetCategory = zod.input<typeof BudgetCategory>;
export type BudgetCategoryOutput = zod.output<typeof BudgetCategory>;
