/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const Category = zod.strictObject({
	id: zod.uuid(),
	name: zod.string(),
	color: zod.string(),
	icon: zod.string(),
});

export type Category = zod.input<typeof Category>;
export type CategoryOutput = zod.output<typeof Category>;
