/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ChatResource } from "./chatResource.zod.ts";

export const chatSummaryTwoMessageCountMin = 0;

export const ChatSummary = ChatResource.and(
	zod.strictObject({
		message_count: zod.int().min(chatSummaryTwoMessageCountMin),
		last_message_at: zod.iso.datetime({ offset: true }).nullish(),
	}),
);

export type ChatSummary = zod.input<typeof ChatSummary>;
export type ChatSummaryOutput = zod.output<typeof ChatSummary>;
