/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ChatSummary } from "./chatSummary.zod.ts";
import { Pagination } from "./pagination.zod.ts";

export const ChatCollection = zod.strictObject({
	chats: zod.array(ChatSummary),
	pagination: Pagination,
});

export type ChatCollection = zod.input<typeof ChatCollection>;
export type ChatCollectionOutput = zod.output<typeof ChatCollection>;
