/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { DashboardAccount } from "./dashboardAccount.zod.ts";
import { Money } from "./money.zod.ts";

export const dashboardAccountGroupAccountsCountMin = 0;

export const DashboardAccountGroup = zod.strictObject({
	key: zod.string().describe("Stable group key, e.g. depository"),
	name: zod.string().describe("Display name for the accountable type"),
	total: Money,
	accounts_count: zod.int().min(dashboardAccountGroupAccountsCountMin),
	accounts: zod.array(DashboardAccount),
});

export type DashboardAccountGroup = zod.input<typeof DashboardAccountGroup>;
export type DashboardAccountGroupOutput = zod.output<typeof DashboardAccountGroup>;
