/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const DashboardSyncLatest = zod.strictObject({
	id: zod.uuid(),
	status: zod.enum(["pending", "syncing", "completed", "failed", "stale"]),
	in_progress: zod.boolean(),
	syncable_type: zod.string(),
	syncable_id: zod.uuid(),
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
	completed_at: zod.iso.datetime({ offset: true }).nullish(),
});

export type DashboardSyncLatest = zod.input<typeof DashboardSyncLatest>;
export type DashboardSyncLatestOutput = zod.output<typeof DashboardSyncLatest>;
