/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { DashboardAccountGroup } from "./dashboardAccountGroup.zod.ts";
import { Money } from "./money.zod.ts";

export const dashboardClassificationGroupAccountsCountMin = 0;

export const DashboardClassificationGroup = zod.strictObject({
	classification: zod.enum(["asset", "liability"]),
	name: zod.string(),
	total: Money,
	syncing: zod.boolean(),
	accounts_count: zod.int().min(dashboardClassificationGroupAccountsCountMin),
	account_groups: zod.array(DashboardAccountGroup),
});

export type DashboardClassificationGroup = zod.input<typeof DashboardClassificationGroup>;
export type DashboardClassificationGroupOutput = zod.output<typeof DashboardClassificationGroup>;
