/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Money } from "./money.zod.ts";

export const DashboardAccount = zod.strictObject({
	id: zod.uuid(),
	name: zod.string(),
	currency: zod.string().describe("Account native currency (ISO 4217)"),
	balance: Money.describe("Native-currency balance"),
	converted_balance: Money.describe("Balance converted to the family primary currency"),
	classification: zod.enum(["asset", "liability"]),
	account_type: zod
		.string()
		.nullish()
		.describe("Accountable type (underscored), e.g. depository, investment"),
	syncing: zod.boolean().describe("True while a visible sync is running for this account"),
});

export type DashboardAccount = zod.input<typeof DashboardAccount>;
export type DashboardAccountOutput = zod.output<typeof DashboardAccount>;
