/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { DashboardTrendValue } from "./dashboardTrendValue.zod.ts";
import { TrendSummary } from "./trendSummary.zod.ts";

export const dashboardTrendValuesMax = 400;

export const DashboardTrend = zod.strictObject({
	period: zod
		.enum([
			"last_7_days",
			"last_30_days",
			"last_90_days",
			"last_365_days",
			"current_month",
			"current_year",
		])
		.describe("Bounded trend period served by the endpoint"),
	start_date: zod.iso.date(),
	end_date: zod.iso.date(),
	interval: zod.string().describe("Series bucket interval (1 day or 1 week)"),
	trend: zod.union([TrendSummary, zod.null()]).exactOptional(),
	values: zod.array(DashboardTrendValue).max(dashboardTrendValuesMax),
});

export type DashboardTrend = zod.input<typeof DashboardTrend>;
export type DashboardTrendOutput = zod.output<typeof DashboardTrend>;
