/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { DashboardSyncLatest } from "./dashboardSyncLatest.zod.ts";

export const DashboardSync = zod.strictObject({
	syncing: zod
		.boolean()
		.describe("True while a recent (visible-window) sync is in progress for the family"),
	stale: zod.boolean().describe("True when the last completed sync is older than 24 hours"),
	last_completed_at: zod.iso.datetime({ offset: true }).nullish(),
	last_activity_at: zod.iso.datetime({ offset: true }).nullish(),
	latest: zod
		.union([DashboardSyncLatest, zod.null()])
		.exactOptional()
		.describe("Most recent family-scoped sync, null when the family never synced"),
});

export type DashboardSync = zod.input<typeof DashboardSync>;
export type DashboardSyncOutput = zod.output<typeof DashboardSync>;
