/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Money } from "./money.zod.ts";
import { TrendSummary } from "./trendSummary.zod.ts";

export const DashboardTrendValue = zod.strictObject({
	date: zod.iso.date().describe("Series point date (ISO 8601)"),
	value: Money,
	trend: zod.union([TrendSummary, zod.null()]).exactOptional(),
});

export type DashboardTrendValue = zod.input<typeof DashboardTrendValue>;
export type DashboardTrendValueOutput = zod.output<typeof DashboardTrendValue>;
