/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const DeleteResponse = zod.object({
  "message": zod.string()
});

export type DeleteResponse = zod.input<typeof DeleteResponse>;
export type DeleteResponseOutput = zod.output<typeof DeleteResponse>;
