/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const DeleteApiV1AccountsIdParams = zod.strictObject({
	confirm: zod.boolean(),
});

export type DeleteApiV1AccountsIdParams = zod.input<typeof DeleteApiV1AccountsIdParams>;
export type DeleteApiV1AccountsIdParamsOutput = zod.output<typeof DeleteApiV1AccountsIdParams>;
