/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const familySettingsMonthStartDayMax = 28;

export const FamilySettings = zod.strictObject({
	id: zod.uuid(),
	name: zod.string().nullish(),
	currency: zod.string(),
	locale: zod.string(),
	date_format: zod.string(),
	country: zod.string().nullish(),
	timezone: zod.string().nullish(),
	month_start_day: zod.int().min(1).max(familySettingsMonthStartDayMax),
	moniker: zod.enum(["Family", "Group"]),
	default_account_sharing: zod.enum(["shared", "private"]),
	custom_enabled_currencies: zod.boolean(),
	enabled_currencies: zod.array(zod.string()),
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
});

export type FamilySettings = zod.input<typeof FamilySettings>;
export type FamilySettingsOutput = zod.output<typeof FamilySettings>;
