/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { FamilyExport } from './familyExport.zod.ts';

export const FamilyExportResponse = zod.object({
  "data": FamilyExport
});

export type FamilyExportResponse = zod.input<typeof FamilyExportResponse>;
export type FamilyExportResponseOutput = zod.output<typeof FamilyExportResponse>;
