/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const familyExportFileByteSizeMin = 0;



export const FamilyExportFile = zod.object({
  "attached": zod.boolean(),
  "byte_size": zod.int().min(familyExportFileByteSizeMin).nullish(),
  "content_type": zod.string().nullish()
});

export type FamilyExportFile = zod.input<typeof FamilyExportFile>;
export type FamilyExportFileOutput = zod.output<typeof FamilyExportFile>;
