/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { FamilyExport } from "./familyExport.zod.ts";
import { Pagination } from "./pagination.zod.ts";

export const familyExportCollectionDataMax = 100;

export const FamilyExportCollection = zod.strictObject({
	data: zod.array(FamilyExport).max(familyExportCollectionDataMax),
	meta: Pagination,
});

export type FamilyExportCollection = zod.input<typeof FamilyExportCollection>;
export type FamilyExportCollectionOutput = zod.output<typeof FamilyExportCollection>;
