/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { FamilyExportFile } from "./familyExportFile.zod.ts";

export const FamilyExport = zod.strictObject({
	id: zod.uuid(),
	status: zod.enum(["pending", "processing", "completed", "failed"]),
	filename: zod.string(),
	downloadable: zod.boolean(),
	download_path: zod.string().nullish(),
	file: FamilyExportFile,
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
});

export type FamilyExport = zod.input<typeof FamilyExport>;
export type FamilyExportOutput = zod.output<typeof FamilyExport>;
