/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1CategoriesParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	roots_only: zod.boolean().exactOptional(),
	parent_id: zod.uuid().exactOptional(),
});

export type GetApiV1CategoriesParams = zod.input<typeof GetApiV1CategoriesParams>;
export type GetApiV1CategoriesParamsOutput = zod.output<typeof GetApiV1CategoriesParams>;
