/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1TransfersParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	status: zod.enum(["pending", "confirmed"]).exactOptional(),
	account_id: zod.uuid().exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
});

export type GetApiV1TransfersParams = zod.input<typeof GetApiV1TransfersParams>;
export type GetApiV1TransfersParamsOutput = zod.output<typeof GetApiV1TransfersParams>;
