/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1RulesParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "resource_type": zod.enum(['transaction']).optional(),
  "active": zod.boolean().optional()
})

export type GetApiV1RulesParams = zod.input<typeof GetApiV1RulesParams>;
export type GetApiV1RulesParamsOutput = zod.output<typeof GetApiV1RulesParams>;
