/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1RecurringTransactionsParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "status": zod.enum(['active', 'inactive']).optional(),
  "account_id": zod.uuid().optional()
})

export type GetApiV1RecurringTransactionsParams = zod.input<typeof GetApiV1RecurringTransactionsParams>;
export type GetApiV1RecurringTransactionsParamsOutput = zod.output<typeof GetApiV1RecurringTransactionsParams>;
