/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1TransactionsParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	account_id: zod.string().exactOptional(),
	category_id: zod.string().exactOptional(),
	merchant_id: zod.string().exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
	min_amount: zod.number().exactOptional(),
	max_amount: zod.number().exactOptional(),
	type: zod.enum(["income", "expense"]).exactOptional(),
	search: zod.string().exactOptional(),
	account_ids: zod.array(zod.string()).exactOptional(),
	category_ids: zod.array(zod.string()).exactOptional(),
	merchant_ids: zod.array(zod.string()).exactOptional(),
	tag_ids: zod.array(zod.string()).exactOptional(),
});

export type GetApiV1TransactionsParams = zod.input<typeof GetApiV1TransactionsParams>;
export type GetApiV1TransactionsParamsOutput = zod.output<typeof GetApiV1TransactionsParams>;
