/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1HoldingsParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	account_id: zod.string().exactOptional(),
	account_ids: zod.array(zod.string()).exactOptional(),
	date: zod.iso.date().exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
	security_id: zod.string().exactOptional(),
});

export type GetApiV1HoldingsParams = zod.input<typeof GetApiV1HoldingsParams>;
export type GetApiV1HoldingsParamsOutput = zod.output<typeof GetApiV1HoldingsParams>;
