/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1SecuritiesParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "ticker": zod.string().optional(),
  "exchange_operating_mic": zod.string().optional(),
  "kind": zod.enum(['standard', 'cash']).optional(),
  "offline": zod.boolean().optional()
})

export type GetApiV1SecuritiesParams = zod.input<typeof GetApiV1SecuritiesParams>;
export type GetApiV1SecuritiesParamsOutput = zod.output<typeof GetApiV1SecuritiesParams>;
