/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1MetadataHeaders = zod.strictObject({
	"X-Api-Key": zod.string().exactOptional(),
});

export type GetApiV1MetadataHeaders = zod.input<typeof GetApiV1MetadataHeaders>;
export type GetApiV1MetadataHeadersOutput = zod.output<typeof GetApiV1MetadataHeaders>;
