/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1SecurityPricesParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	security_id: zod.uuid().exactOptional(),
	currency: zod.string().exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
	provisional: zod.boolean().exactOptional(),
});

export type GetApiV1SecurityPricesParams = zod.input<typeof GetApiV1SecurityPricesParams>;
export type GetApiV1SecurityPricesParamsOutput = zod.output<typeof GetApiV1SecurityPricesParams>;
