/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1BudgetsParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "start_date": zod.iso.date().optional(),
  "end_date": zod.iso.date().optional()
})

export type GetApiV1BudgetsParams = zod.input<typeof GetApiV1BudgetsParams>;
export type GetApiV1BudgetsParamsOutput = zod.output<typeof GetApiV1BudgetsParams>;
