/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1SecuritiesParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	ticker: zod.string().exactOptional(),
	exchange_operating_mic: zod.string().exactOptional(),
	kind: zod.enum(["standard", "cash"]).exactOptional(),
	offline: zod.boolean().exactOptional(),
});

export type GetApiV1SecuritiesParams = zod.input<typeof GetApiV1SecuritiesParams>;
export type GetApiV1SecuritiesParamsOutput = zod.output<typeof GetApiV1SecuritiesParams>;
