/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1TransfersParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "status": zod.enum(['pending', 'confirmed']).optional(),
  "account_id": zod.uuid().optional(),
  "start_date": zod.iso.date().optional(),
  "end_date": zod.iso.date().optional()
})

export type GetApiV1TransfersParams = zod.input<typeof GetApiV1TransfersParams>;
export type GetApiV1TransfersParamsOutput = zod.output<typeof GetApiV1TransfersParams>;
