/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1BudgetCategoriesParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "budget_id": zod.uuid().optional(),
  "category_id": zod.uuid().optional(),
  "start_date": zod.iso.date().optional(),
  "end_date": zod.iso.date().optional()
})

export type GetApiV1BudgetCategoriesParams = zod.input<typeof GetApiV1BudgetCategoriesParams>;
export type GetApiV1BudgetCategoriesParamsOutput = zod.output<typeof GetApiV1BudgetCategoriesParams>;
