/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1TradesParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	account_id: zod.string().exactOptional(),
	account_ids: zod.array(zod.string()).exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
});

export type GetApiV1TradesParams = zod.input<typeof GetApiV1TradesParams>;
export type GetApiV1TradesParamsOutput = zod.output<typeof GetApiV1TradesParams>;
