/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1AccountsIdParams = zod.object({
  "include_disabled": zod.boolean().optional()
})

export type GetApiV1AccountsIdParams = zod.input<typeof GetApiV1AccountsIdParams>;
export type GetApiV1AccountsIdParamsOutput = zod.output<typeof GetApiV1AccountsIdParams>;
