/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1BudgetCategoriesParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	budget_id: zod.uuid().exactOptional(),
	category_id: zod.uuid().exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
});

export type GetApiV1BudgetCategoriesParams = zod.input<typeof GetApiV1BudgetCategoriesParams>;
export type GetApiV1BudgetCategoriesParamsOutput = zod.output<
	typeof GetApiV1BudgetCategoriesParams
>;
