/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1HoldingsParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "account_id": zod.string().optional(),
  "account_ids": zod.array(zod.string()).optional(),
  "date": zod.iso.date().optional(),
  "start_date": zod.iso.date().optional(),
  "end_date": zod.iso.date().optional(),
  "security_id": zod.string().optional()
})

export type GetApiV1HoldingsParams = zod.input<typeof GetApiV1HoldingsParams>;
export type GetApiV1HoldingsParamsOutput = zod.output<typeof GetApiV1HoldingsParams>;
