/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1SyncsParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional()
})

export type GetApiV1SyncsParams = zod.input<typeof GetApiV1SyncsParams>;
export type GetApiV1SyncsParamsOutput = zod.output<typeof GetApiV1SyncsParams>;
