/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1BalanceSheetParams = zod.strictObject({
	period: zod
		.enum([
			"last_7_days",
			"last_30_days",
			"last_90_days",
			"last_365_days",
			"current_month",
			"current_year",
		])
		.exactOptional(),
});

export type GetApiV1BalanceSheetParams = zod.input<typeof GetApiV1BalanceSheetParams>;
export type GetApiV1BalanceSheetParamsOutput = zod.output<typeof GetApiV1BalanceSheetParams>;
