/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1TransactionsParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "account_id": zod.string().optional(),
  "category_id": zod.string().optional(),
  "merchant_id": zod.string().optional(),
  "start_date": zod.iso.date().optional(),
  "end_date": zod.iso.date().optional(),
  "min_amount": zod.number().optional(),
  "max_amount": zod.number().optional(),
  "type": zod.enum(['income', 'expense']).optional(),
  "search": zod.string().optional(),
  "account_ids": zod.array(zod.string()).optional(),
  "category_ids": zod.array(zod.string()).optional(),
  "merchant_ids": zod.array(zod.string()).optional(),
  "tag_ids": zod.array(zod.string()).optional()
})

export type GetApiV1TransactionsParams = zod.input<typeof GetApiV1TransactionsParams>;
export type GetApiV1TransactionsParamsOutput = zod.output<typeof GetApiV1TransactionsParams>;
