/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1RecurringTransactionsParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	status: zod.enum(["active", "inactive"]).exactOptional(),
	account_id: zod.uuid().exactOptional(),
});

export type GetApiV1RecurringTransactionsParams = zod.input<
	typeof GetApiV1RecurringTransactionsParams
>;
export type GetApiV1RecurringTransactionsParamsOutput = zod.output<
	typeof GetApiV1RecurringTransactionsParams
>;
