/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const GetApiV1BudgetsParams = zod.strictObject({
	page: zod.int().exactOptional(),
	per_page: zod.int().exactOptional(),
	start_date: zod.iso.date().exactOptional(),
	end_date: zod.iso.date().exactOptional(),
});

export type GetApiV1BudgetsParams = zod.input<typeof GetApiV1BudgetsParams>;
export type GetApiV1BudgetsParamsOutput = zod.output<typeof GetApiV1BudgetsParams>;
