/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const GetApiV1SecurityPricesParams = zod.object({
  "page": zod.int().optional(),
  "per_page": zod.int().optional(),
  "security_id": zod.uuid().optional(),
  "currency": zod.string().optional(),
  "start_date": zod.iso.date().optional(),
  "end_date": zod.iso.date().optional(),
  "provisional": zod.boolean().optional()
})

export type GetApiV1SecurityPricesParams = zod.input<typeof GetApiV1SecurityPricesParams>;
export type GetApiV1SecurityPricesParamsOutput = zod.output<typeof GetApiV1SecurityPricesParams>;
