/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { Holding } from './holding.zod.ts';
import { Pagination } from './pagination.zod.ts';

export const HoldingCollection = zod.object({
  "holdings": zod.array(Holding),
  "pagination": Pagination
});

export type HoldingCollection = zod.input<typeof HoldingCollection>;
export type HoldingCollectionOutput = zod.output<typeof HoldingCollection>;
