/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ImportPreflight } from "./importPreflight.zod.ts";

export const ImportPreflightResponse = zod.strictObject({
	data: ImportPreflight,
});

export type ImportPreflightResponse = zod.input<typeof ImportPreflightResponse>;
export type ImportPreflightResponseOutput = zod.output<typeof ImportPreflightResponse>;
