/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ImportStatusSummary } from "./importStatusSummary.zod.ts";

export const ImportStatusDetail = ImportStatusSummary.and(
	zod.strictObject({
		cleaned: zod.boolean(),
		publishable: zod.boolean(),
		revertable: zod.boolean(),
	}),
);

export type ImportStatusDetail = zod.input<typeof ImportStatusDetail>;
export type ImportStatusDetailOutput = zod.output<typeof ImportStatusDetail>;
