/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { ImportSession } from './importSession.zod.ts';

export const ImportSessionResponse = zod.object({
  "data": ImportSession
});

export type ImportSessionResponse = zod.input<typeof ImportSessionResponse>;
export type ImportSessionResponseOutput = zod.output<typeof ImportSessionResponse>;
