/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ImportPreflightError = zod.strictObject({
	code: zod.string(),
	message: zod.string(),
});

export type ImportPreflightError = zod.input<typeof ImportPreflightError>;
export type ImportPreflightErrorOutput = zod.output<typeof ImportPreflightError>;
