/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ImportConfiguration = zod.strictObject({
	date_col_label: zod.string().nullish(),
	amount_col_label: zod.string().nullish(),
	name_col_label: zod.string().nullish(),
	category_col_label: zod.string().nullish(),
	tags_col_label: zod.string().nullish(),
	notes_col_label: zod.string().nullish(),
	account_col_label: zod.string().nullish(),
	date_format: zod.string().nullish(),
	number_format: zod.string().nullish(),
	signage_convention: zod.string().nullish(),
});

export type ImportConfiguration = zod.input<typeof ImportConfiguration>;
export type ImportConfigurationOutput = zod.output<typeof ImportConfiguration>;
