/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ImportDetail } from "./importDetail.zod.ts";

export const ImportResponse = zod.strictObject({
	data: ImportDetail,
});

export type ImportResponse = zod.input<typeof ImportResponse>;
export type ImportResponseOutput = zod.output<typeof ImportResponse>;
