/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const ImportVerificationReadback = zod.object({
  "status": zod.enum(['not_verified', 'matched', 'mismatch', 'failed', 'reverted']).optional(),
  "checked_at": zod.iso.datetime({"offset":true}).nullish(),
  "expected_record_counts": zod.record(zod.string(), zod.int()).optional(),
  "before_counts": zod.record(zod.string(), zod.int()).optional(),
  "after_counts": zod.record(zod.string(), zod.int()).optional(),
  "actual_delta_counts": zod.record(zod.string(), zod.int()).optional(),
  "checked_counts": zod.record(zod.string(), zod.int()).optional(),
  "mismatches": zod.record(zod.string(), zod.object({
  "expected": zod.int(),
  "actual": zod.int()
})).optional(),
  "error": zod.string().nullish()
}).describe('SureImport only. Expected NDJSON counts compared to family-scoped database readback after publish.');

export type ImportVerificationReadback = zod.input<typeof ImportVerificationReadback>;
export type ImportVerificationReadbackOutput = zod.output<typeof ImportVerificationReadback>;
