/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const ImportStatusSummary = zod.object({
  "uploaded": zod.boolean(),
  "configured": zod.boolean(),
  "terminal": zod.boolean()
});

export type ImportStatusSummary = zod.input<typeof ImportStatusSummary>;
export type ImportStatusSummaryOutput = zod.output<typeof ImportStatusSummary>;
