/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const importPreflightContentByteSizeMin = 0;

export const ImportPreflightContent = zod.strictObject({
	filename: zod.string(),
	content_type: zod.string(),
	byte_size: zod.int().min(importPreflightContentByteSizeMin),
});

export type ImportPreflightContent = zod.input<typeof ImportPreflightContent>;
export type ImportPreflightContentOutput = zod.output<typeof ImportPreflightContent>;
