/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ImportVerificationReadback } from "./importVerificationReadback.zod.ts";

export const ImportVerification = zod
	.strictObject({
		expected_record_counts: zod.record(zod.string(), zod.int()),
		readback: ImportVerificationReadback,
	})
	.describe("SureImport only. Captured at upload and completed after import publish.");

export type ImportVerification = zod.input<typeof ImportVerification>;
export type ImportVerificationOutput = zod.output<typeof ImportVerification>;
