/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ImportStatusSummary } from "./importStatusSummary.zod.ts";

export const importSummaryRowsCountMin = 0;

export const ImportSummary = zod.strictObject({
	id: zod.uuid(),
	type: zod.enum([
		"TransactionImport",
		"TradeImport",
		"AccountImport",
		"MintImport",
		"ActualImport",
		"YnabImport",
		"CategoryImport",
		"RuleImport",
		"MerchantImport",
		"PdfImport",
		"QifImport",
		"SureImport",
	]),
	status: zod.enum(["pending", "complete", "importing", "reverting", "revert_failed", "failed"]),
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
	account_id: zod.uuid().nullish(),
	rows_count: zod.int().min(importSummaryRowsCountMin).exactOptional(),
	error: zod.string().nullish(),
	status_detail: ImportStatusSummary,
});

export type ImportSummary = zod.input<typeof ImportSummary>;
export type ImportSummaryOutput = zod.output<typeof ImportSummary>;
