/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const Insight = zod.strictObject({
	id: zod.uuid(),
	type: zod.string(),
	title: zod.string(),
	body: zod.string(),
	priority: zod.enum(["high", "medium", "low"]),
	status: zod.enum(["active", "read"]),
	generated_at: zod.iso.datetime({ offset: true }).nullish(),
});

export type Insight = zod.input<typeof Insight>;
export type InsightOutput = zod.output<typeof Insight>;
