/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { Insight } from './insight.zod.ts';

export const InsightCollection = zod.object({
  "insights": zod.array(Insight)
});

export type InsightCollection = zod.input<typeof InsightCollection>;
export type InsightCollectionOutput = zod.output<typeof InsightCollection>;
