/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { MerchantDetail } from './merchantDetail.zod.ts';

export const MerchantImportResult = zod.object({
  "imported": zod.int().describe('Number of merchants successfully created'),
  "skipped": zod.int().describe('Number of rows skipped (duplicates or invalid)'),
  "merchants": zod.array(MerchantDetail)
});

export type MerchantImportResult = zod.input<typeof MerchantImportResult>;
export type MerchantImportResultOutput = zod.output<typeof MerchantImportResult>;
