/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const Merchant = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "website_url": zod.url().nullish(),
  "logo_url": zod.url().nullish()
});

export type Merchant = zod.input<typeof Merchant>;
export type MerchantOutput = zod.output<typeof Merchant>;
