/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const MerchantRequest = zod.strictObject({
	merchant: zod.strictObject({
		name: zod
			.string()
			.exactOptional()
			.describe("Merchant name. Required when creating a merchant."),
		color: zod.string().exactOptional().describe("Hex color used for the fallback avatar"),
		website_url: zod.url().nullish(),
		logo_url: zod.url().nullish().describe("Direct merchant logo URL"),
	}),
});

export type MerchantRequest = zod.input<typeof MerchantRequest>;
export type MerchantRequestOutput = zod.output<typeof MerchantRequest>;
