/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const MfaRequiredResponse = zod.object({
  "error": zod.string(),
  "mfa_required": zod.boolean()
});

export type MfaRequiredResponse = zod.input<typeof MfaRequiredResponse>;
export type MfaRequiredResponseOutput = zod.output<typeof MfaRequiredResponse>;
