/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const Money = zod.object({
  "amount": zod.string().describe('Numeric amount as string'),
  "currency": zod.string().describe('ISO 4217 currency code'),
  "formatted": zod.string().describe('Locale-formatted money string')
});

export type Money = zod.input<typeof Money>;
export type MoneyOutput = zod.output<typeof Money>;
