/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const paginationTotalCountMin = 0;

export const paginationTotalPagesMin = 0;

export const Pagination = zod.strictObject({
	page: zod.int().min(1),
	per_page: zod.int().min(1),
	total_count: zod.int().min(paginationTotalCountMin),
	total_pages: zod.int().min(paginationTotalPagesMin),
});

export type Pagination = zod.input<typeof Pagination>;
export type PaginationOutput = zod.output<typeof Pagination>;
