/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PatchApiV1TradesIdBody = zod.object({
  "trade": zod.object({
  "date": zod.iso.date().optional(),
  "qty": zod.number().optional(),
  "price": zod.number().optional(),
  "type": zod.enum(['buy', 'sell', 'dividend', 'deposit', 'withdrawal', 'interest']).optional(),
  "nature": zod.enum(['inflow', 'outflow']).optional(),
  "name": zod.string().optional(),
  "notes": zod.string().optional(),
  "currency": zod.string().optional(),
  "investment_activity_label": zod.string().optional(),
  "category_id": zod.uuid().optional()
}).optional()
})

export type PatchApiV1TradesIdBody = zod.input<typeof PatchApiV1TradesIdBody>;
export type PatchApiV1TradesIdBodyOutput = zod.output<typeof PatchApiV1TradesIdBody>;
