/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PatchApiV1TransactionsIdBody = zod.object({
  "transaction": zod.object({
  "date": zod.iso.date().optional(),
  "amount": zod.number().optional(),
  "name": zod.string().optional(),
  "description": zod.string().optional().describe('Alternative to name field'),
  "notes": zod.string().optional(),
  "currency": zod.string().optional().describe('Currency code'),
  "category_id": zod.uuid().optional(),
  "merchant_id": zod.uuid().optional(),
  "nature": zod.enum(['income', 'expense', 'inflow', 'outflow']).optional(),
  "tag_ids": zod.array(zod.uuid()).optional().describe('Array of tag IDs to assign. Omit to preserve existing tags; use [] to clear all tags.')
}).optional()
})

export type PatchApiV1TransactionsIdBody = zod.input<typeof PatchApiV1TransactionsIdBody>;
export type PatchApiV1TransactionsIdBodyOutput = zod.output<typeof PatchApiV1TransactionsIdBody>;
