/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PatchApiV1AuthEnableAi200 = zod.object({
  "user": zod.object({
  "id": zod.uuid().optional(),
  "email": zod.string().optional(),
  "first_name": zod.string().nullish(),
  "last_name": zod.string().nullish(),
  "ui_layout": zod.enum(['dashboard', 'intro']).optional(),
  "ai_enabled": zod.boolean().optional()
}).optional()
})

export type PatchApiV1AuthEnableAi200 = zod.input<typeof PatchApiV1AuthEnableAi200>;
export type PatchApiV1AuthEnableAi200Output = zod.output<typeof PatchApiV1AuthEnableAi200>;
