/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AccountsIdArchiveParams = zod.strictObject({
	confirm: zod.boolean(),
});

export type PostApiV1AccountsIdArchiveParams = zod.input<typeof PostApiV1AccountsIdArchiveParams>;
export type PostApiV1AccountsIdArchiveParamsOutput = zod.output<
	typeof PostApiV1AccountsIdArchiveParams
>;
