/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PostApiV1ChatsBody = zod.object({
  "title": zod.string(),
  "message": zod.string().optional().describe('Optional initial message in the chat'),
  "model": zod.string().optional().describe('Optional OpenAI model identifier')
})

export type PostApiV1ChatsBody = zod.input<typeof PostApiV1ChatsBody>;
export type PostApiV1ChatsBodyOutput = zod.output<typeof PostApiV1ChatsBody>;
