/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthSsoCreateAccountBody = zod.strictObject({
	linking_code: zod.string().describe("One-time linking code from mobile SSO onboarding redirect"),
	first_name: zod
		.string()
		.exactOptional()
		.describe("First name (overrides value from SSO provider if provided)"),
	last_name: zod
		.string()
		.exactOptional()
		.describe("Last name (overrides value from SSO provider if provided)"),
});

export type PostApiV1AuthSsoCreateAccountBody = zod.input<typeof PostApiV1AuthSsoCreateAccountBody>;
export type PostApiV1AuthSsoCreateAccountBodyOutput = zod.output<
	typeof PostApiV1AuthSsoCreateAccountBody
>;
