/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PostApiV1AuthLoginBody = zod.object({
  "email": zod.email(),
  "password": zod.string(),
  "otp_code": zod.string().nullish().describe('TOTP code if MFA is enabled'),
  "device": zod.object({
  "device_id": zod.string(),
  "device_name": zod.string(),
  "device_type": zod.string(),
  "os_version": zod.string(),
  "app_version": zod.string()
})
})

export type PostApiV1AuthLoginBody = zod.input<typeof PostApiV1AuthLoginBody>;
export type PostApiV1AuthLoginBodyOutput = zod.output<typeof PostApiV1AuthLoginBody>;
