/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthLogoutBody = zod.strictObject({
	refresh_token: zod
		.string()
		.nullish()
		.describe(
			"Refresh token identifying the token pair to revoke when revoking by param instead of bearer token",
		),
});

export type PostApiV1AuthLogoutBody = zod.input<typeof PostApiV1AuthLogoutBody>;
export type PostApiV1AuthLogoutBodyOutput = zod.output<typeof PostApiV1AuthLogoutBody>;
