/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PostApiV1ChatsChatIdMessagesBody = zod.object({
  "content": zod.string(),
  "model": zod.string().optional()
})

export type PostApiV1ChatsChatIdMessagesBody = zod.input<typeof PostApiV1ChatsChatIdMessagesBody>;
export type PostApiV1ChatsChatIdMessagesBodyOutput = zod.output<typeof PostApiV1ChatsChatIdMessagesBody>;
