/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PostApiV1AuthSsoLink200 = zod.object({
  "access_token": zod.string().optional(),
  "refresh_token": zod.string().optional(),
  "token_type": zod.string().optional(),
  "expires_in": zod.int().optional(),
  "created_at": zod.int().optional(),
  "user": zod.object({
  "id": zod.uuid().optional(),
  "email": zod.string().optional(),
  "first_name": zod.string().optional(),
  "last_name": zod.string().optional(),
  "ui_layout": zod.enum(['dashboard', 'intro']).optional(),
  "ai_enabled": zod.boolean().optional()
}).optional()
})

export type PostApiV1AuthSsoLink200 = zod.input<typeof PostApiV1AuthSsoLink200>;
export type PostApiV1AuthSsoLink200Output = zod.output<typeof PostApiV1AuthSsoLink200>;
