/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';



export const PostApiV1ImportSessionsBody = zod.object({
  "type": zod.enum(['SureImport']).optional().describe('Import session type. Only SureImport is supported.'),
  "client_session_id": zod.string().nullish().describe('Client-provided idempotency key for the full import session.'),
  "expected_chunks": zod.int().min(1).nullish().describe('Expected number of ordered chunks before publish is allowed.')
})

export type PostApiV1ImportSessionsBody = zod.input<typeof PostApiV1ImportSessionsBody>;
export type PostApiV1ImportSessionsBodyOutput = zod.output<typeof PostApiV1ImportSessionsBody>;
