/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthLogout200 = zod.strictObject({
	revoked: zod.boolean().exactOptional(),
});

export type PostApiV1AuthLogout200 = zod.input<typeof PostApiV1AuthLogout200>;
export type PostApiV1AuthLogout200Output = zod.output<typeof PostApiV1AuthLogout200>;
