/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthSsoExchange200 = zod.strictObject({
	access_token: zod.string().exactOptional(),
	refresh_token: zod.string().exactOptional(),
	token_type: zod.string().exactOptional(),
	expires_in: zod.int().exactOptional(),
	created_at: zod.int().exactOptional(),
	user: zod
		.strictObject({
			id: zod.uuid().exactOptional(),
			email: zod.string().exactOptional(),
			first_name: zod.string().exactOptional(),
			last_name: zod.string().exactOptional(),
			ui_layout: zod.enum(["dashboard", "intro"]).exactOptional(),
			ai_enabled: zod.boolean().exactOptional(),
		})
		.exactOptional(),
});

export type PostApiV1AuthSsoExchange200 = zod.input<typeof PostApiV1AuthSsoExchange200>;
export type PostApiV1AuthSsoExchange200Output = zod.output<typeof PostApiV1AuthSsoExchange200>;
