/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1ChatsBody = zod.strictObject({
	title: zod.string(),
	message: zod.string().exactOptional().describe("Optional initial message in the chat"),
	model: zod.string().exactOptional().describe("Optional OpenAI model identifier"),
});

export type PostApiV1ChatsBody = zod.input<typeof PostApiV1ChatsBody>;
export type PostApiV1ChatsBodyOutput = zod.output<typeof PostApiV1ChatsBody>;
