/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const postApiV1ImportsPreflightBodyRowsToSkipMin = 0;


export const PostApiV1ImportsPreflightBody = zod.object({
  "raw_file_content": zod.string().optional().describe('Raw CSV or Sure NDJSON content as a string. CSV content is limited to 10MB.'),
  "file": zod.instanceof(Blob).optional().describe('CSV or Sure NDJSON upload when using multipart/form-data. CSV files are limited to 10MB.'),
  "type": zod.enum(['TransactionImport', 'TradeImport', 'AccountImport', 'MintImport', 'ActualImport', 'YnabImport', 'CategoryImport', 'RuleImport', 'MerchantImport', 'PdfImport', 'QifImport', 'SureImport']).optional().describe('Import type to validate (defaults to TransactionImport)'),
  "account_id": zod.uuid().optional().describe('Account ID used for account-scoped CSV import validation'),
  "date_col_label": zod.string().optional().describe('CSV imports only. Header name for the date column'),
  "amount_col_label": zod.string().optional().describe('CSV imports only. Header name for the amount column'),
  "name_col_label": zod.string().optional().describe('CSV imports only. Header name for the transaction name column'),
  "category_col_label": zod.string().optional().describe('CSV imports only. Header name for the category column'),
  "tags_col_label": zod.string().optional().describe('CSV imports only. Header name for the tags column'),
  "notes_col_label": zod.string().optional().describe('CSV imports only. Header name for the notes column'),
  "account_col_label": zod.string().optional().describe('CSV imports only. Header name for the account column'),
  "qty_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the quantity column'),
  "ticker_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the ticker column'),
  "price_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the price column'),
  "entity_type_col_label": zod.string().optional().describe('CSV imports only. Header name for the entity type column'),
  "currency_col_label": zod.string().optional().describe('CSV imports only. Header name for the currency column'),
  "exchange_operating_mic_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the exchange operating MIC column'),
  "date_format": zod.string().optional().describe('CSV imports only. Date format pattern'),
  "number_format": zod.enum(['1,234.56', '1.234,56', '1 234,56', '1,234']).optional().describe('CSV imports only. Number format for parsing amounts'),
  "signage_convention": zod.enum(['inflows_positive', 'inflows_negative']).optional().describe('CSV imports only. How to interpret positive/negative amounts'),
  "col_sep": zod.enum([',', ';']).optional().describe('CSV imports only. Column separator'),
  "rows_to_skip": zod.int().min(postApiV1ImportsPreflightBodyRowsToSkipMin).optional().describe('CSV imports only. Number of leading rows to skip before reading headers'),
  "amount_type_strategy": zod.enum(['signed_amount', 'custom_column']).optional().describe('CSV imports only. Amount parsing strategy'),
  "amount_type_inflow_value": zod.string().optional().describe('CSV imports only. Column value that marks an amount as an inflow when using custom_column strategy')
})

export type PostApiV1ImportsPreflightBody = zod.input<typeof PostApiV1ImportsPreflightBody>;
export type PostApiV1ImportsPreflightBodyOutput = zod.output<typeof PostApiV1ImportsPreflightBody>;
