/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const PostApiV1TagsBody = zod.object({
  "tag": zod.object({
  "name": zod.string().describe('Tag name (required)'),
  "color": zod.string().optional().describe('Hex color code (optional, auto-assigned if not provided)')
})
})

export type PostApiV1TagsBody = zod.input<typeof PostApiV1TagsBody>;
export type PostApiV1TagsBodyOutput = zod.output<typeof PostApiV1TagsBody>;
