/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthSsoExchangeBody = zod.strictObject({
	code: zod.string().describe("One-time authorization code from mobile SSO callback"),
});

export type PostApiV1AuthSsoExchangeBody = zod.input<typeof PostApiV1AuthSsoExchangeBody>;
export type PostApiV1AuthSsoExchangeBodyOutput = zod.output<typeof PostApiV1AuthSsoExchangeBody>;
