/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthSsoCreateAccount422 = zod.strictObject({
	errors: zod.array(zod.string()).exactOptional(),
});

export type PostApiV1AuthSsoCreateAccount422 = zod.input<typeof PostApiV1AuthSsoCreateAccount422>;
export type PostApiV1AuthSsoCreateAccount422Output = zod.output<
	typeof PostApiV1AuthSsoCreateAccount422
>;
