/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const PostApiV1AuthRefresh200 = zod.strictObject({
	access_token: zod.string().exactOptional(),
	refresh_token: zod.string().exactOptional(),
	token_type: zod.string().exactOptional(),
	expires_in: zod.int().exactOptional(),
	created_at: zod.int().exactOptional(),
});

export type PostApiV1AuthRefresh200 = zod.input<typeof PostApiV1AuthRefresh200>;
export type PostApiV1AuthRefresh200Output = zod.output<typeof PostApiV1AuthRefresh200>;
