/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { ProviderConnection } from "./providerConnection.zod.ts";

export const ProviderConnectionCollection = zod.strictObject({
	data: zod.array(ProviderConnection),
});

export type ProviderConnectionCollection = zod.input<typeof ProviderConnectionCollection>;
export type ProviderConnectionCollectionOutput = zod.output<typeof ProviderConnectionCollection>;
