/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { ProviderConnectionAccounts } from './providerConnectionAccounts.zod.ts';
import { ProviderConnectionInstitution } from './providerConnectionInstitution.zod.ts';
import { ProviderConnectionSync } from './providerConnectionSync.zod.ts';

export const ProviderConnection = zod.object({
  "id": zod.uuid(),
  "provider": zod.string(),
  "provider_type": zod.string(),
  "name": zod.string(),
  "status": zod.string().nullable(),
  "requires_update": zod.boolean().nullable().describe('False when the provider item does not expose this status.'),
  "credentials_configured": zod.boolean().nullable().describe('False when credential readiness is unknown.'),
  "scheduled_for_deletion": zod.boolean().nullable().describe('False when the provider item does not expose this status.'),
  "pending_account_setup": zod.boolean().nullable().describe('False when account setup state is unknown.'),
  "institution": ProviderConnectionInstitution,
  "accounts": ProviderConnectionAccounts,
  "sync": ProviderConnectionSync,
  "created_at": zod.iso.datetime({"offset":true}),
  "updated_at": zod.iso.datetime({"offset":true})
});

export type ProviderConnection = zod.input<typeof ProviderConnection>;
export type ProviderConnectionOutput = zod.output<typeof ProviderConnection>;
