/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ProviderConnectionSyncLatest = zod.strictObject({
	id: zod.uuid(),
	status: zod.string(),
	created_at: zod.iso.datetime({ offset: true }),
	syncing_at: zod.iso.datetime({ offset: true }).nullish(),
	completed_at: zod.iso.datetime({ offset: true }).nullish(),
	failed_at: zod.iso.datetime({ offset: true }).nullish(),
	error: zod
		.strictObject({
			present: zod.boolean().describe("Always true when this object is present."),
			message: zod
				.string()
				.nullish()
				.describe(
					"Stable sanitized error category message; raw provider error text is never exposed.",
				),
		})
		.nullish()
		.describe(
			"Sanitized latest sync error summary. Null when the latest sync is not failed or stale.",
		),
});

export type ProviderConnectionSyncLatest = zod.input<typeof ProviderConnectionSyncLatest>;
export type ProviderConnectionSyncLatestOutput = zod.output<typeof ProviderConnectionSyncLatest>;
