/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { ProviderConnectionSyncLatest } from './providerConnectionSyncLatest.zod.ts';

export const ProviderConnectionSync = zod.object({
  "syncing": zod.boolean(),
  "status_summary": zod.string().nullish(),
  "last_synced_at": zod.iso.datetime({"offset":true}).nullish(),
  "latest": zod.union([ProviderConnectionSyncLatest,zod.null()]).optional()
});

export type ProviderConnectionSync = zod.input<typeof ProviderConnectionSync>;
export type ProviderConnectionSyncOutput = zod.output<typeof ProviderConnectionSync>;
