/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ProviderConnectionInstitution = zod.strictObject({
	name: zod.string().nullable(),
	domain: zod.string().nullish(),
	url: zod.string().nullish(),
});

export type ProviderConnectionInstitution = zod.input<typeof ProviderConnectionInstitution>;
export type ProviderConnectionInstitutionOutput = zod.output<typeof ProviderConnectionInstitution>;
