/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Pagination } from "./pagination.zod.ts";
import { RecurringTransaction } from "./recurringTransaction.zod.ts";

export const RecurringTransactionCollection = zod.strictObject({
	recurring_transactions: zod.array(RecurringTransaction),
	pagination: Pagination,
});

export type RecurringTransactionCollection = zod.input<typeof RecurringTransactionCollection>;
export type RecurringTransactionCollectionOutput = zod.output<
	typeof RecurringTransactionCollection
>;
