/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Account } from "./account.zod.ts";
import { Merchant } from "./merchant.zod.ts";

export const recurringTransactionExpectedDayOfMonthMax = 31;

export const recurringTransactionOccurrenceCountMin = 0;

export const RecurringTransaction = zod.strictObject({
	id: zod.uuid(),
	amount: zod.string(),
	amount_cents: zod.int().describe("Amount in currency minor units"),
	currency: zod.string(),
	expected_day_of_month: zod.int().min(1).max(recurringTransactionExpectedDayOfMonthMax),
	last_occurrence_date: zod.iso.date(),
	next_expected_date: zod.iso.date(),
	status: zod.enum(["active", "inactive"]),
	occurrence_count: zod.int().min(recurringTransactionOccurrenceCountMin),
	name: zod.string().nullish(),
	manual: zod.boolean(),
	expected_amount_min: zod.string().nullish(),
	expected_amount_min_cents: zod
		.int()
		.nullish()
		.describe("Minimum expected amount in currency minor units"),
	expected_amount_max: zod.string().nullish(),
	expected_amount_max_cents: zod
		.int()
		.nullish()
		.describe("Maximum expected amount in currency minor units"),
	expected_amount_avg: zod.string().nullish(),
	expected_amount_avg_cents: zod
		.int()
		.nullish()
		.describe("Average expected amount in currency minor units"),
	account: zod.union([Account, zod.null()]).exactOptional(),
	merchant: zod.union([Merchant, zod.null()]).exactOptional(),
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
});

export type RecurringTransaction = zod.input<typeof RecurringTransaction>;
export type RecurringTransactionOutput = zod.output<typeof RecurringTransaction>;
