/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { TransferTransactionSide } from "./transferTransactionSide.zod.ts";

export const RejectedTransfer = zod.strictObject({
	id: zod.uuid(),
	inflow_transaction: TransferTransactionSide,
	outflow_transaction: TransferTransactionSide,
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
});

export type RejectedTransfer = zod.input<typeof RejectedTransfer>;
export type RejectedTransferOutput = zod.output<typeof RejectedTransfer>;
