/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const resetStatusResponseCountsAccountStatementsMin = 0;

export const resetStatusResponseCountsFamilyExportsMin = 0;

export const resetStatusResponseCountsImportsMin = 0;

export const resetStatusResponseCountsImportSessionsMin = 0;

export const resetStatusResponseCountsImportSourceMappingsMin = 0;

export const resetStatusResponseCountsImportRowsMin = 0;

export const resetStatusResponseCountsImportMappingsMin = 0;

export const resetStatusResponseCountsAccountsMin = 0;

export const resetStatusResponseCountsAccountSharesMin = 0;

export const resetStatusResponseCountsAccountProvidersMin = 0;

export const resetStatusResponseCountsEntriesMin = 0;

export const resetStatusResponseCountsTransactionsMin = 0;

export const resetStatusResponseCountsTransfersMin = 0;

export const resetStatusResponseCountsRejectedTransfersMin = 0;

export const resetStatusResponseCountsValuationsMin = 0;

export const resetStatusResponseCountsTradesMin = 0;

export const resetStatusResponseCountsHoldingsMin = 0;

export const resetStatusResponseCountsBalancesMin = 0;

export const resetStatusResponseCountsRecurringTransactionsMin = 0;

export const resetStatusResponseCountsRulesMin = 0;

export const resetStatusResponseCountsRuleActionsMin = 0;

export const resetStatusResponseCountsRuleConditionsMin = 0;

export const resetStatusResponseCountsRuleRunsMin = 0;

export const resetStatusResponseCountsBudgetsMin = 0;

export const resetStatusResponseCountsBudgetCategoriesMin = 0;

export const resetStatusResponseCountsCategoriesMin = 0;

export const resetStatusResponseCountsTagsMin = 0;

export const resetStatusResponseCountsTaggingsMin = 0;

export const resetStatusResponseCountsMerchantsMin = 0;

export const resetStatusResponseCountsFamilyMerchantAssociationsMin = 0;

export const resetStatusResponseCountsProviderItemsMin = 0;

export const resetStatusResponseCountsActiveStorageAttachmentsMin = 0;

export const resetStatusResponseCountsPlaidItemsMin = 0;

export const ResetStatusResponse = zod.strictObject({
	status: zod
		.enum(["complete", "data_remaining"])
		.describe("Counts-based family reset status at response time."),
	family_id: zod.uuid().describe("UUID of the family whose reset target counts were checked."),
	reset_complete: zod
		.boolean()
		.describe(
			"True when all reset target counts are zero at response time. This is a family data snapshot, not a durable per-job completion record.",
		),
	counts: zod.strictObject({
		account_statements: zod.int().min(resetStatusResponseCountsAccountStatementsMin),
		family_exports: zod.int().min(resetStatusResponseCountsFamilyExportsMin),
		imports: zod.int().min(resetStatusResponseCountsImportsMin),
		import_sessions: zod.int().min(resetStatusResponseCountsImportSessionsMin),
		import_source_mappings: zod.int().min(resetStatusResponseCountsImportSourceMappingsMin),
		import_rows: zod.int().min(resetStatusResponseCountsImportRowsMin),
		import_mappings: zod.int().min(resetStatusResponseCountsImportMappingsMin),
		accounts: zod.int().min(resetStatusResponseCountsAccountsMin),
		account_shares: zod.int().min(resetStatusResponseCountsAccountSharesMin),
		account_providers: zod.int().min(resetStatusResponseCountsAccountProvidersMin),
		entries: zod.int().min(resetStatusResponseCountsEntriesMin),
		transactions: zod.int().min(resetStatusResponseCountsTransactionsMin),
		transfers: zod.int().min(resetStatusResponseCountsTransfersMin),
		rejected_transfers: zod.int().min(resetStatusResponseCountsRejectedTransfersMin),
		valuations: zod.int().min(resetStatusResponseCountsValuationsMin),
		trades: zod.int().min(resetStatusResponseCountsTradesMin),
		holdings: zod.int().min(resetStatusResponseCountsHoldingsMin),
		balances: zod.int().min(resetStatusResponseCountsBalancesMin),
		recurring_transactions: zod.int().min(resetStatusResponseCountsRecurringTransactionsMin),
		rules: zod.int().min(resetStatusResponseCountsRulesMin),
		rule_actions: zod.int().min(resetStatusResponseCountsRuleActionsMin),
		rule_conditions: zod.int().min(resetStatusResponseCountsRuleConditionsMin),
		rule_runs: zod.int().min(resetStatusResponseCountsRuleRunsMin),
		budgets: zod.int().min(resetStatusResponseCountsBudgetsMin),
		budget_categories: zod.int().min(resetStatusResponseCountsBudgetCategoriesMin),
		categories: zod.int().min(resetStatusResponseCountsCategoriesMin),
		tags: zod.int().min(resetStatusResponseCountsTagsMin),
		taggings: zod.int().min(resetStatusResponseCountsTaggingsMin),
		merchants: zod.int().min(resetStatusResponseCountsMerchantsMin),
		family_merchant_associations: zod
			.int()
			.min(resetStatusResponseCountsFamilyMerchantAssociationsMin),
		provider_items: zod.int().min(resetStatusResponseCountsProviderItemsMin),
		active_storage_attachments: zod.int().min(resetStatusResponseCountsActiveStorageAttachmentsMin),
		plaid_items: zod.int().min(resetStatusResponseCountsPlaidItemsMin),
	}),
});

export type ResetStatusResponse = zod.input<typeof ResetStatusResponse>;
export type ResetStatusResponseOutput = zod.output<typeof ResetStatusResponse>;
