/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const ResetInitiatedResponse = zod.strictObject({
	message: zod.string(),
	status: zod.enum(["queued"]),
	job_id: zod
		.string()
		.describe(
			"Informational Active Job identifier returned by the queue adapter; reset status is family-scoped, not job-scoped.",
		),
	family_id: zod.uuid().describe("UUID of the family being reset."),
	status_url: zod.string(),
});

export type ResetInitiatedResponse = zod.input<typeof ResetInitiatedResponse>;
export type ResetInitiatedResponseOutput = zod.output<typeof ResetInitiatedResponse>;
