/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const RetryResponse = zod.object({
  "message": zod.string(),
  "message_id": zod.uuid()
});

export type RetryResponse = zod.input<typeof RetryResponse>;
export type RetryResponseOutput = zod.output<typeof RetryResponse>;
