/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { RuleRun } from './ruleRun.zod.ts';

export const RuleRunCollection = zod.object({
  "data": zod.array(RuleRun),
  "meta": zod.object({
  "current_page": zod.int(),
  "next_page": zod.int().nullish(),
  "prev_page": zod.int().nullish(),
  "total_pages": zod.int(),
  "total_count": zod.int(),
  "per_page": zod.int()
})
});

export type RuleRunCollection = zod.input<typeof RuleRunCollection>;
export type RuleRunCollectionOutput = zod.output<typeof RuleRunCollection>;
