/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { Rule } from './rule.zod.ts';

export const RuleResponse = zod.object({
  "data": Rule
});

export type RuleResponse = zod.input<typeof RuleResponse>;
export type RuleResponseOutput = zod.output<typeof RuleResponse>;
