/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { RuleRun } from "./ruleRun.zod.ts";

export const RuleRunResponse = zod.strictObject({
	data: RuleRun,
});

export type RuleRunResponse = zod.input<typeof RuleRunResponse>;
export type RuleRunResponseOutput = zod.output<typeof RuleRunResponse>;
