/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { Pagination } from './pagination.zod.ts';
import { Security } from './security.zod.ts';

export const SecurityCollection = zod.object({
  "securities": zod.array(Security),
  "pagination": Pagination
});

export type SecurityCollection = zod.input<typeof SecurityCollection>;
export type SecurityCollectionOutput = zod.output<typeof SecurityCollection>;
