/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const SuccessMessage = zod.object({
  "message": zod.string()
});

export type SuccessMessage = zod.input<typeof SuccessMessage>;
export type SuccessMessageOutput = zod.output<typeof SuccessMessage>;
