/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const SyncableSummary = zod.strictObject({
	type: zod.string(),
	id: zod.uuid(),
	name: zod.string().nullish(),
});

export type SyncableSummary = zod.input<typeof SyncableSummary>;
export type SyncableSummaryOutput = zod.output<typeof SyncableSummary>;
