/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';
import { SyncableSummary } from './syncableSummary.zod.ts';
import { SyncErrorSummary } from './syncErrorSummary.zod.ts';

export const syncResourceChildrenCountMin = 0;



export const SyncResource = zod.object({
  "id": zod.uuid(),
  "status": zod.enum(['pending', 'syncing', 'completed', 'failed', 'stale']),
  "in_progress": zod.boolean(),
  "terminal": zod.boolean(),
  "syncable": SyncableSummary,
  "parent_id": zod.uuid().nullish(),
  "children_count": zod.int().min(syncResourceChildrenCountMin),
  "window_start_date": zod.iso.date().nullish(),
  "window_end_date": zod.iso.date().nullish(),
  "pending_at": zod.iso.datetime({"offset":true}).nullish(),
  "syncing_at": zod.iso.datetime({"offset":true}).nullish(),
  "completed_at": zod.iso.datetime({"offset":true}).nullish(),
  "failed_at": zod.iso.datetime({"offset":true}).nullish(),
  "error": zod.union([SyncErrorSummary,zod.null()]).optional(),
  "created_at": zod.iso.datetime({"offset":true}),
  "updated_at": zod.iso.datetime({"offset":true})
});

export type SyncResource = zod.input<typeof SyncResource>;
export type SyncResourceOutput = zod.output<typeof SyncResource>;
