/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

export const SyncErrorSummary = zod.strictObject({
	message: zod.string(),
});

export type SyncErrorSummary = zod.input<typeof SyncErrorSummary>;
export type SyncErrorSummaryOutput = zod.output<typeof SyncErrorSummary>;
