/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const Tag = zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "color": zod.string()
});

export type Tag = zod.input<typeof Tag>;
export type TagOutput = zod.output<typeof Tag>;
