/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { TagDetail } from "./tagDetail.zod.ts";

export const TagCollection = zod.array(TagDetail);

export type TagCollection = zod.input<typeof TagCollection>;
export type TagCollectionOutput = zod.output<typeof TagCollection>;
