/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Account } from "./account.zod.ts";
import { Category } from "./category.zod.ts";
import { Merchant } from "./merchant.zod.ts";
import { Tag } from "./tag.zod.ts";
import { Transfer } from "./transfer.zod.ts";

export const Transaction = zod.strictObject({
	id: zod.uuid(),
	date: zod.iso.date(),
	amount: zod.string(),
	currency: zod.string(),
	name: zod.string(),
	notes: zod.string().nullish(),
	external_id: zod.string().nullish(),
	source: zod.string().nullish(),
	user_modified: zod.boolean().exactOptional(),
	classification: zod.string(),
	account: Account,
	category: zod.union([Category, zod.null()]).exactOptional(),
	merchant: zod.union([Merchant, zod.null()]).exactOptional(),
	tags: zod.array(Tag),
	transfer: zod.union([Transfer, zod.null()]).exactOptional(),
	created_at: zod.iso.datetime({ offset: true }),
	updated_at: zod.iso.datetime({ offset: true }),
});

export type Transaction = zod.input<typeof Transaction>;
export type TransactionOutput = zod.output<typeof Transaction>;
