/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Transaction } from "./transaction.zod.ts";

export const TransactionSplit = zod.strictObject({
	parent_transaction_id: zod.uuid(),
	splits: zod.array(Transaction),
});

export type TransactionSplit = zod.input<typeof TransactionSplit>;
export type TransactionSplitOutput = zod.output<typeof TransactionSplit>;
