/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

export const TransactionResponse = zod.object({
  "id": zod.uuid(),
  "date": zod.iso.date(),
  "amount": zod.string(),
  "currency": zod.string(),
  "name": zod.string(),
  "entryable_type": zod.string(),
  "account": zod.object({
  "id": zod.uuid(),
  "name": zod.string(),
  "account_type": zod.string().nullable()
})
});

export type TransactionResponse = zod.input<typeof TransactionResponse>;
export type TransactionResponseOutput = zod.output<typeof TransactionResponse>;
