/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Money } from "./money.zod.ts";

export const TrendSummary = zod.strictObject({
	value: Money,
	percent: zod
		.number()
		.nullish()
		.describe("Percentage change, null when the base is zero (see percent_formatted)"),
	percent_formatted: zod
		.string()
		.describe("Display string for the percentage change (carries ±∞ when percent is null)"),
	current: Money,
	previous: Money,
	direction: zod.enum(["up", "down", "flat"]),
	color: zod.string(),
	icon: zod.string(),
});

export type TrendSummary = zod.input<typeof TrendSummary>;
export type TrendSummaryOutput = zod.output<typeof TrendSummary>;
