/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";
import { Pagination } from "./pagination.zod.ts";
import { Valuation } from "./valuation.zod.ts";

export const ValuationCollection = zod.strictObject({
	valuations: zod.array(Valuation),
	pagination: Pagination,
});

export type ValuationCollection = zod.input<typeof ValuationCollection>;
export type ValuationCollectionOutput = zod.output<typeof ValuationCollection>;
