/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SpaRouteImport } from "./routes/spa"
import { Route as TransactionsRouteImport } from "./routes/transactions"
import { Route as SpaIndexRouteImport } from "./routes/spa/index"
import { Route as SpaAccountsRouteImport } from "./routes/spa/accounts"

const SpaRoute = SpaRouteImport.update({
  id: "/spa",
  path: "/spa",
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: "/transactions",
  path: "/transactions",
  getParentRoute: () => rootRouteImport,
} as any)
const SpaIndexRoute = SpaIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SpaRoute,
} as any)
const SpaAccountsRoute = SpaAccountsRouteImport.update({
  id: "/accounts",
  path: "/accounts",
  getParentRoute: () => SpaRoute,
} as any)

export interface FileRoutesByFullPath {
  "/spa": typeof SpaRouteWithChildren
  "/transactions": typeof TransactionsRoute
  "/spa/accounts": typeof SpaAccountsRoute
  "/spa/": typeof SpaIndexRoute
}
export interface FileRoutesByTo {
  "/transactions": typeof TransactionsRoute
  "/spa/accounts": typeof SpaAccountsRoute
  "/spa": typeof SpaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/spa": typeof SpaRouteWithChildren
  "/transactions": typeof TransactionsRoute
  "/spa/accounts": typeof SpaAccountsRoute
  "/spa/": typeof SpaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/spa" | "/transactions" | "/spa/accounts" | "/spa/"
  fileRoutesByTo: FileRoutesByTo
  to: "/transactions" | "/spa/accounts" | "/spa"
  id: "__root__" | "/spa" | "/transactions" | "/spa/accounts" | "/spa/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SpaRoute: typeof SpaRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/spa": {
      id: "/spa"
      path: "/spa"
      fullPath: "/spa"
      preLoaderRoute: typeof SpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/transactions": {
      id: "/transactions"
      path: "/transactions"
      fullPath: "/transactions"
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/spa/": {
      id: "/spa/"
      path: "/"
      fullPath: "/spa/"
      preLoaderRoute: typeof SpaIndexRouteImport
      parentRoute: typeof SpaRoute
    }
    "/spa/accounts": {
      id: "/spa/accounts"
      path: "/accounts"
      fullPath: "/spa/accounts"
      preLoaderRoute: typeof SpaAccountsRouteImport
      parentRoute: typeof SpaRoute
    }
  }
}

interface SpaRouteChildren {
  SpaAccountsRoute: typeof SpaAccountsRoute
  SpaIndexRoute: typeof SpaIndexRoute
}

const SpaRouteChildren: SpaRouteChildren = {
  SpaAccountsRoute: SpaAccountsRoute,
  SpaIndexRoute: SpaIndexRoute,
}

const SpaRouteWithChildren = SpaRoute._addFileChildren(SpaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SpaRoute: SpaRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
