/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

import {
  ErrorResponse,
  RuleCollection,
  RuleResponse
} from '../../models';


/**
 * @summary List rules
 */
export const GetApiV1RulesQueryParams = zod.object({
  "page": zod.int().optional().describe('Page number (default: 1)'),
  "per_page": zod.int().optional().describe('Items per page (default: 25, max: 100)'),
  "resource_type": zod.enum(['transaction']).optional().describe('Filter by rule resource type'),
  "active": zod.boolean().optional().describe('Filter by active status')
})

export const GetApiV1Rules200Response = RuleCollection

export const GetApiV1Rules401Response = ErrorResponse

export const GetApiV1Rules403Response = ErrorResponse

export const GetApiV1Rules422Response = ErrorResponse

/**
 * @summary Retrieve a rule
 */
export const GetApiV1RulesIdParams = zod.object({
  "id": zod.string().describe('Rule ID')
})

export const GetApiV1RulesId200Response = RuleResponse

export const GetApiV1RulesId401Response = ErrorResponse

export const GetApiV1RulesId403Response = ErrorResponse

export const GetApiV1RulesId404Response = ErrorResponse

