/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod/mini";

/**
 * @summary List transactions for the browser SPA
 */

export const getApiSpaTransactionsQueryPerPageMax = 100;

export const GetApiSpaTransactionsQueryParams = /*#__PURE__*/ zod.object({
  page: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod
      .int()
      .check(/*#__PURE__*/ zod.gte(1)),
  ),
  per_page: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod
      .int()
      .check(/*#__PURE__*/ zod.gte(1))
      .check(/*#__PURE__*/ zod.lte(getApiSpaTransactionsQueryPerPageMax)),
  ),
  search: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.string()),
  start_date: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.date()),
  end_date: /*#__PURE__*/ zod.optional(/*#__PURE__*/ zod.iso.date()),
  types: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(
      /*#__PURE__*/ zod.enum(["income", "expense", "transfer"]),
    ),
  ),
  status: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.enum(["pending", "confirmed"])),
  ),
  accounts: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  ),
  account_ids: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.uuid()),
  ),
  categories: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  ),
  merchants: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  ),
  tags: /*#__PURE__*/ zod.optional(
    /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
  ),
});

export const getApiSpaTransactions200ResponseTransactionsItemAmountCentsMin = 0;

export const getApiSpaTransactions200ResponseSummaryCountMin = 0;

export const getApiSpaTransactions200ResponsePaginationTotalCountMin = 0;

export const getApiSpaTransactions200ResponsePaginationTotalPagesMin = 0;

export const GetApiSpaTransactions200Response = /*#__PURE__*/ zod.strictObject({
  transactions: /*#__PURE__*/ zod.array(
    /*#__PURE__*/ zod.strictObject({
      id: /*#__PURE__*/ zod.uuid(),
      entry_id: /*#__PURE__*/ zod.uuid(),
      date: /*#__PURE__*/ zod.iso.date(),
      amount: /*#__PURE__*/ zod.string(),
      amount_cents: /*#__PURE__*/ zod
        .int()
        .check(
          /*#__PURE__*/ zod.gte(
            getApiSpaTransactions200ResponseTransactionsItemAmountCentsMin,
          ),
        ),
      signed_amount_cents: /*#__PURE__*/ zod.int(),
      currency: /*#__PURE__*/ zod.string(),
      name: /*#__PURE__*/ zod.string(),
      notes: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
      classification: /*#__PURE__*/ zod.string(),
      pending: /*#__PURE__*/ zod.boolean(),
      excluded: /*#__PURE__*/ zod.boolean(),
      detail_path: /*#__PURE__*/ zod.string(),
      account: /*#__PURE__*/ zod.strictObject({
        id: /*#__PURE__*/ zod.uuid(),
        name: /*#__PURE__*/ zod.string(),
        account_type: /*#__PURE__*/ zod.string(),
        path: /*#__PURE__*/ zod.string(),
      }),
      category: /*#__PURE__*/ zod.optional(
        /*#__PURE__*/ zod.union([
          /*#__PURE__*/ zod.strictObject({
            id: /*#__PURE__*/ zod.uuid(),
            name: /*#__PURE__*/ zod.string(),
            color: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
            icon: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
          }),
          /*#__PURE__*/ zod.null(),
        ]),
      ),
      merchant: /*#__PURE__*/ zod.optional(
        /*#__PURE__*/ zod.union([
          /*#__PURE__*/ zod.strictObject({
            id: /*#__PURE__*/ zod.uuid(),
            name: /*#__PURE__*/ zod.string(),
          }),
          /*#__PURE__*/ zod.null(),
        ]),
      ),
      tags: /*#__PURE__*/ zod.array(
        /*#__PURE__*/ zod.strictObject({
          id: /*#__PURE__*/ zod.uuid(),
          name: /*#__PURE__*/ zod.string(),
          color: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
        }),
      ),
    }),
  ),
  summary: /*#__PURE__*/ zod.strictObject({
    count: /*#__PURE__*/ zod
      .int()
      .check(
        /*#__PURE__*/ zod.gte(getApiSpaTransactions200ResponseSummaryCountMin),
      ),
    income: /*#__PURE__*/ zod.string(),
    expense: /*#__PURE__*/ zod.string(),
    transfer_inflow: /*#__PURE__*/ zod.string(),
    transfer_outflow: /*#__PURE__*/ zod.string(),
    currency: /*#__PURE__*/ zod.string(),
  }),
  pagination: /*#__PURE__*/ zod.strictObject({
    page: /*#__PURE__*/ zod
      .int()
      .check(/*#__PURE__*/ zod.gte(1)),
    per_page: /*#__PURE__*/ zod
      .int()
      .check(/*#__PURE__*/ zod.gte(1)),
    total_count: /*#__PURE__*/ zod
      .int()
      .check(
        /*#__PURE__*/ zod.gte(
          getApiSpaTransactions200ResponsePaginationTotalCountMin,
        ),
      ),
    total_pages: /*#__PURE__*/ zod
      .int()
      .check(
        /*#__PURE__*/ zod.gte(
          getApiSpaTransactions200ResponsePaginationTotalPagesMin,
        ),
      ),
  }),
});

export const GetApiSpaTransactions401Response = /*#__PURE__*/ zod.strictObject({
  error: /*#__PURE__*/ zod.string(),
  message: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  details: /*#__PURE__*/ zod.nullish(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
      /*#__PURE__*/ zod.looseObject({}),
    ]),
  ),
  errors: /*#__PURE__*/ zod
    .nullish(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()))
    .check(
      /*#__PURE__*/ zod.describe(
        "Validation error messages (alternative to details used by trades, valuations, etc.)",
      ),
    ),
});

export const GetApiSpaTransactions422Response = /*#__PURE__*/ zod.strictObject({
  error: /*#__PURE__*/ zod.string(),
  message: /*#__PURE__*/ zod.nullish(/*#__PURE__*/ zod.string()),
  details: /*#__PURE__*/ zod.nullish(
    /*#__PURE__*/ zod.union([
      /*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()),
      /*#__PURE__*/ zod.looseObject({}),
    ]),
  ),
  errors: /*#__PURE__*/ zod
    .nullish(/*#__PURE__*/ zod.array(/*#__PURE__*/ zod.string()))
    .check(
      /*#__PURE__*/ zod.describe(
        "Validation error messages (alternative to details used by trades, valuations, etc.)",
      ),
    ),
});
