/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

import {
  ErrorResponse,
  FamilyExportCollection,
  FamilyExportResponse
} from '../../models';


/**
 * @summary Lists family exports
 */
export const GetApiV1FamilyExportsQueryParams = zod.object({
  "page": zod.int().optional().describe('Page number (default: 1)'),
  "per_page": zod.int().optional().describe('Items per page (default: 25, max: 100)')
})

export const GetApiV1FamilyExports200Response = FamilyExportCollection

export const GetApiV1FamilyExports401Response = ErrorResponse

export const GetApiV1FamilyExports403Response = ErrorResponse

/**
 * @summary Queues a family export
 */
export const PostApiV1FamilyExportsBody = zod.object({

}).describe('Family export creation does not accept request parameters.')

export const PostApiV1FamilyExports202Response = FamilyExportResponse

export const PostApiV1FamilyExports401Response = ErrorResponse

export const PostApiV1FamilyExports403Response = ErrorResponse

export const PostApiV1FamilyExports422Response = ErrorResponse

/**
 * @summary Shows a family export
 */
export const GetApiV1FamilyExportsIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiV1FamilyExportsId200Response = FamilyExportResponse

export const GetApiV1FamilyExportsId401Response = ErrorResponse

export const GetApiV1FamilyExportsId403Response = ErrorResponse

export const GetApiV1FamilyExportsId404Response = ErrorResponse

/**
 * @summary Downloads a completed family export
 */
export const GetApiV1FamilyExportsIdDownloadParams = zod.object({
  "id": zod.uuid()
})

export const GetApiV1FamilyExportsIdDownload302Response = zod.unknown()

export const GetApiV1FamilyExportsIdDownload401Response = ErrorResponse

export const GetApiV1FamilyExportsIdDownload403Response = ErrorResponse

export const GetApiV1FamilyExportsIdDownload404Response = ErrorResponse

export const GetApiV1FamilyExportsIdDownload409Response = ErrorResponse

