/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import {
	AccountCollection,
	AccountCreateRequest,
	AccountDetail,
	AccountUpdateRequest,
	DeleteResponse,
	ErrorResponse,
} from "../../models";

/**
 * @summary List accounts
 */
export const GetApiV1AccountsQueryParams = zod.strictObject({
	page: zod.int().exactOptional().describe("Page number (default: 1)"),
	per_page: zod.int().exactOptional().describe("Items per page (default: 25, max: 100)"),
	include_disabled: zod
		.boolean()
		.exactOptional()
		.describe("Include disabled accounts in the response. Defaults to false."),
});

export const GetApiV1Accounts200Response = AccountCollection;

/**
 * @summary Create a manual account
 */
export const PostApiV1AccountsBody = AccountCreateRequest;

export const PostApiV1Accounts201Response = AccountDetail;

export const PostApiV1Accounts403Response = ErrorResponse;

export const PostApiV1Accounts422Response = ErrorResponse;

/**
 * @summary Retrieve an account
 */
export const GetApiV1AccountsIdParams = zod.strictObject({
	id: zod.uuid().describe("Account ID"),
});

export const GetApiV1AccountsIdQueryParams = zod.strictObject({
	include_disabled: zod
		.boolean()
		.exactOptional()
		.describe("Allow retrieving a disabled account. Defaults to false."),
});

export const GetApiV1AccountsId200Response = AccountDetail;

export const GetApiV1AccountsId401Response = ErrorResponse;

export const GetApiV1AccountsId403Response = ErrorResponse;

export const GetApiV1AccountsId404Response = ErrorResponse;

/**
 * @summary Update a manual account
 */
export const PatchApiV1AccountsIdParams = zod.strictObject({
	id: zod.uuid().describe("Account ID"),
});

export const PatchApiV1AccountsIdBody = AccountUpdateRequest;

export const PatchApiV1AccountsId200Response = AccountDetail;

export const PatchApiV1AccountsId400Response = ErrorResponse;

export const PatchApiV1AccountsId401Response = ErrorResponse;

export const PatchApiV1AccountsId403Response = ErrorResponse;

export const PatchApiV1AccountsId404Response = ErrorResponse;

export const PatchApiV1AccountsId422Response = ErrorResponse;

/**
 * @summary Delete a manual account
 */
export const DeleteApiV1AccountsIdParams = zod.strictObject({
	id: zod.uuid().describe("Account ID"),
});

export const DeleteApiV1AccountsIdQueryParams = zod.strictObject({
	confirm: zod
		.boolean()
		.describe("Must be true to confirm deletion. Deleted accounts are marked for deletion."),
});

export const DeleteApiV1AccountsId200Response = DeleteResponse;

export const DeleteApiV1AccountsId401Response = ErrorResponse;

export const DeleteApiV1AccountsId403Response = ErrorResponse;

export const DeleteApiV1AccountsId404Response = ErrorResponse;

export const DeleteApiV1AccountsId422Response = ErrorResponse;

/**
 * @summary Archive a manual account
 */
export const PostApiV1AccountsIdArchiveParams = zod.strictObject({
	id: zod.uuid().describe("Account ID"),
});

export const PostApiV1AccountsIdArchiveQueryParams = zod.strictObject({
	confirm: zod
		.boolean()
		.describe("Must be true to confirm archiving. Archived accounts are disabled."),
});

export const PostApiV1AccountsIdArchive200Response = AccountDetail;

export const PostApiV1AccountsIdArchive401Response = ErrorResponse;

export const PostApiV1AccountsIdArchive403Response = ErrorResponse;

export const PostApiV1AccountsIdArchive404Response = ErrorResponse;

export const PostApiV1AccountsIdArchive422Response = ErrorResponse;
