/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import { ErrorResponse, ImportSessionResponse } from "../../models";

/**
 * Create or idempotently retrieve a multi-file SureImport session keyed by client_session_id.
 * @summary Create import session
 */

export const PostApiV1ImportSessionsBody = zod.strictObject({
	type: zod
		.enum(["SureImport"])
		.exactOptional()
		.describe("Import session type. Only SureImport is supported."),
	client_session_id: zod
		.string()
		.nullish()
		.describe("Client-provided idempotency key for the full import session."),
	expected_chunks: zod
		.int()
		.min(1)
		.nullish()
		.describe("Expected number of ordered chunks before publish is allowed."),
});

export const PostApiV1ImportSessions201Response = ImportSessionResponse;

export const PostApiV1ImportSessions401Response = ErrorResponse;

export const PostApiV1ImportSessions403Response = ErrorResponse;

export const PostApiV1ImportSessions409Response = ErrorResponse;

export const PostApiV1ImportSessions422Response = ErrorResponse;

/**
 * Retrieve import session status, chunk status, per-entity summary counts, and safe error details.
 * @summary Retrieve import session
 */
export const GetApiV1ImportSessionsIdParams = zod.strictObject({
	id: zod.string().describe("Import session ID"),
});

export const GetApiV1ImportSessionsId200Response = ImportSessionResponse;

export const GetApiV1ImportSessionsId401Response = ErrorResponse;

export const GetApiV1ImportSessionsId403Response = ErrorResponse;

export const GetApiV1ImportSessionsId404Response = ErrorResponse;

/**
 * Attach an ordered Sure NDJSON chunk to an import session. Chunks are idempotent by sequence and client_chunk_id with content verification.
 * @summary Upload import session chunk
 */
export const PostApiV1ImportSessionsIdChunksParams = zod.strictObject({
	id: zod.string().describe("Import session ID"),
});

export const PostApiV1ImportSessionsIdChunksBody = zod.strictObject({
	sequence: zod
		.int()
		.min(1)
		.describe(
			"One-based chunk sequence. Earlier dependency chunks must have lower sequence numbers.",
		),
	client_chunk_id: zod
		.string()
		.nullish()
		.describe("Client-provided idempotency key for this chunk."),
	raw_file_content: zod
		.string()
		.describe("Raw Sure NDJSON content. Each chunk is limited to 10MB."),
});

export const PostApiV1ImportSessionsIdChunks201Response = ImportSessionResponse;

export const PostApiV1ImportSessionsIdChunks401Response = ErrorResponse;

export const PostApiV1ImportSessionsIdChunks403Response = ErrorResponse;

export const PostApiV1ImportSessionsIdChunks404Response = ErrorResponse;

export const PostApiV1ImportSessionsIdChunks409Response = ErrorResponse;

export const PostApiV1ImportSessionsIdChunks422Response = ErrorResponse;

/**
 * Queue ordered chunk processing for a SureImport session. Later chunks can reference source IDs mapped by earlier chunks.
 * @summary Publish import session
 */
export const PostApiV1ImportSessionsIdPublishParams = zod.strictObject({
	id: zod.string().describe("Import session ID"),
});

export const PostApiV1ImportSessionsIdPublish202Response = ImportSessionResponse;

export const PostApiV1ImportSessionsIdPublish401Response = ErrorResponse;

export const PostApiV1ImportSessionsIdPublish403Response = ErrorResponse;

export const PostApiV1ImportSessionsIdPublish404Response = ErrorResponse;

export const PostApiV1ImportSessionsIdPublish409Response = ErrorResponse;

export const PostApiV1ImportSessionsIdPublish422Response = ErrorResponse;

export const PostApiV1ImportSessionsIdPublish503Response = ErrorResponse;
