/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

import {
  ErrorResponse,
  SyncCollection,
  SyncResponse
} from '../../models';


/**
 * List sanitized sync status history for the authenticated user's family, accounts, and provider connections.
 * @summary Lists sync history
 */
export const GetApiV1SyncsQueryParams = zod.object({
  "page": zod.int().optional().describe('Page number (default: 1)'),
  "per_page": zod.int().optional().describe('Items per page (default: 25, max: 100)')
})

export const GetApiV1Syncs200Response = SyncCollection

export const GetApiV1Syncs401Response = ErrorResponse

export const GetApiV1Syncs403Response = ErrorResponse

/**
 * Return the most recently created sanitized sync status for the authenticated user's family, or data: null when no sync exists.
 * @summary Shows the latest sync
 */
export const GetApiV1SyncsLatest200Response = SyncResponse

export const GetApiV1SyncsLatest401Response = ErrorResponse

export const GetApiV1SyncsLatest403Response = ErrorResponse

/**
 * Return sanitized status metadata for a single family-scoped sync.
 * @summary Shows a sync
 */
export const GetApiV1SyncsIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiV1SyncsId200Response = SyncResponse

export const GetApiV1SyncsId401Response = ErrorResponse

export const GetApiV1SyncsId403Response = ErrorResponse

export const GetApiV1SyncsId404Response = ErrorResponse

