/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import { ChatCollection, ChatDetail, ErrorResponse } from "../../models";

/**
 * @summary List chats
 */
export const GetApiV1Chats200Response = ChatCollection;

export const GetApiV1Chats403Response = ErrorResponse;

/**
 * @summary Create chat
 */
export const PostApiV1ChatsBody = zod.strictObject({
	title: zod.string(),
	message: zod.string().exactOptional().describe("Optional initial message in the chat"),
	model: zod.string().exactOptional().describe("Optional OpenAI model identifier"),
});

export const PostApiV1Chats201Response = ChatDetail;

export const PostApiV1Chats422Response = ErrorResponse;

/**
 * @summary Retrieve a chat
 */
export const GetApiV1ChatsIdParams = zod.strictObject({
	id: zod.string().describe("Chat ID"),
});

export const GetApiV1ChatsId200Response = ChatDetail;

export const GetApiV1ChatsId404Response = ErrorResponse;

/**
 * @summary Update a chat
 */
export const PatchApiV1ChatsIdParams = zod.strictObject({
	id: zod.string().describe("Chat ID"),
});

export const PatchApiV1ChatsIdBody = zod.strictObject({
	title: zod.string().exactOptional(),
});

export const PatchApiV1ChatsId200Response = ChatDetail;

export const PatchApiV1ChatsId404Response = ErrorResponse;

export const PatchApiV1ChatsId422Response = ErrorResponse;

/**
 * @summary Delete a chat
 */
export const DeleteApiV1ChatsIdParams = zod.strictObject({
	id: zod.string().describe("Chat ID"),
});

export const DeleteApiV1ChatsId204Response = zod.void();

export const DeleteApiV1ChatsId404Response = ErrorResponse;
