// GENERATED — do not edit by hand.
// Source: design/tokens/sure.tokens.json
// Build:  npm run tokens:build
//
// Semantic Sure theme for apps/web. Every value is resolved from the
// canonical token JSON (DTCG refs inlined, sure.dark applied per theme), so
// this file MUST stay in sync via the generator — never hand-edit.
//
// PRODUCT CODE RULE: consume only the semantic `vars` below (plus the
// theme classes). Raw palette ladders (gray/red/green/…) are intentionally
// NOT exported; import those and the drift test fails. Details:
// apps/web/src/styles/README.md
import * as stylex from "@stylexjs/stylex";

// The semantic contract: color, typography, radius, shadow, motion, and
// chart tokens. Raw palette ladders are intentionally absent.
export type SureTokenName = "bgInverse" | "bgInverseHover" | "bgLoader" | "bgOverlay" | "bgSubdued" | "borderDestructive" | "borderDivider" | "borderInverse" | "borderPrimary" | "borderSecondary" | "borderSolid" | "borderSubdued" | "buttonBgDestructive" | "buttonBgDestructiveHover" | "buttonBgDisabled" | "buttonBgGhostHover" | "buttonBgOutlineHover" | "buttonBgPrimary" | "buttonBgPrimaryHover" | "buttonBgSecondary" | "buttonBgSecondaryHover" | "buttonBgSecondaryStrong" | "buttonBgSecondaryStrongHover" | "chartUnallocatedFill" | "chartUnusedFill" | "container" | "containerHover" | "containerInset" | "containerInsetHover" | "destructive" | "destructiveSubtle" | "focusRing" | "fontMono" | "fontSans" | "fontWeightMedium" | "fontWeightSemibold" | "info" | "link" | "motionStrokeFill" | "navIndicator" | "radiusLg" | "radiusMd" | "shadow" | "shadowBorderLg" | "shadowBorderMd" | "shadowBorderSm" | "shadowBorderXl" | "shadowBorderXs" | "shadowLg" | "shadowMd" | "shadowSm" | "shadowXl" | "shadowXs" | "success" | "surface" | "surfaceHover" | "surfaceInset" | "surfaceInsetHover" | "tabBgGroup" | "tabItemActive" | "tabItemHover" | "tertiary" | "textDestructiveStrong" | "textInfoStrong" | "textInverse" | "textPrimary" | "textSecondary" | "textSecondaryStrong" | "textSubdued" | "textSuccessStrong" | "textWarningStrong" | "toggleTrack" | "warning";

// Light defaults.
export const vars = stylex.defineVars({
	bgInverse: "#242424",
	bgInverseHover: "#363636",
	bgLoader: "#F0F0F0",
	bgOverlay: "color-mix(in srgb, #F0F0F0 50%, transparent)",
	bgSubdued: "#9E9E9E",
	borderDestructive: "#F13636",
	borderDivider: "color-mix(in srgb, #0B0B0B 8%, transparent)",
	borderInverse: "color-mix(in srgb, #ffffff 10%, transparent)",
	borderPrimary: "color-mix(in srgb, #0B0B0B 15%, transparent)",
	borderSecondary: "color-mix(in srgb, #0B0B0B 10%, transparent)",
	borderSolid: "#0B0B0B",
	borderSubdued: "color-mix(in srgb, #0B0B0B 5%, transparent)",
	buttonBgDestructive: "#C91313",
	buttonBgDestructiveHover: "#A40E0E",
	buttonBgDisabled: "#F7F7F7",
	buttonBgGhostHover: "#F7F7F7",
	buttonBgOutlineHover: "#F0F0F0",
	buttonBgPrimary: "#171717",
	buttonBgPrimaryHover: "#242424",
	buttonBgSecondary: "#F7F7F7",
	buttonBgSecondaryHover: "#F0F0F0",
	buttonBgSecondaryStrong: "#E7E7E7",
	buttonBgSecondaryStrongHover: "#CFCFCF",
	chartUnallocatedFill: "#F7F7F7",
	chartUnusedFill: "#E7E7E7",
	container: "#ffffff",
	containerHover: "#F7F7F7",
	containerInset: "#F7F7F7",
	containerInsetHover: "#F0F0F0",
	destructive: "#F13636",
	destructiveSubtle: "#FEB9B3",
	focusRing: "color-mix(in srgb, #0B0B0B 50%, transparent)",
	fontMono: "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
	fontSans: "'Geist', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
	fontWeightMedium: "500",
	fontWeightSemibold: "600",
	info: "#1570EF",
	link: "#1570EF",
	motionStrokeFill: "stroke-fill 3s 300ms forwards",
	navIndicator: "#0B0B0B",
	radiusLg: "10px",
	radiusMd: "8px",
	shadow: "color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowBorderLg: "0px 12px 16px -4px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderMd: "0px 4px 8px -2px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderSm: "0px 1px 6px 0px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderXl: "0px 20px 24px -4px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderXs: "0px 1px 2px 0px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowLg: "0px 12px 16px -4px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowMd: "0px 4px 8px -2px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowSm: "0px 1px 6px 0px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowXl: "0px 20px 24px -4px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowXs: "0px 1px 2px 0px color-mix(in srgb, #0B0B0B 6%, transparent)",
	success: "#078C52",
	surface: "#F7F7F7",
	surfaceHover: "#F0F0F0",
	surfaceInset: "#F0F0F0",
	surfaceInsetHover: "#E7E7E7",
	tabBgGroup: "#F7F7F7",
	tabItemActive: "#ffffff",
	tabItemHover: "#E7E7E7",
	tertiary: "color-mix(in srgb, #0B0B0B 8%, transparent)",
	textDestructiveStrong: "#C91313",
	textInfoStrong: "#175CD3",
	textInverse: "#ffffff",
	textPrimary: "#171717",
	textSecondary: "#737373",
	textSecondaryStrong: "#5C5C5C",
	textSubdued: "#9E9E9E",
	textSuccessStrong: "#05603A",
	textWarningStrong: "#B54708",
	toggleTrack: "#CFCFCF",
	warning: "#DC6803",
});

// Explicit light theme (for [data-theme="light"] overrides of the OS default).
export const sureLightTheme = stylex.createTheme(vars, {
	bgInverse: "#242424",
	bgInverseHover: "#363636",
	bgLoader: "#F0F0F0",
	bgOverlay: "color-mix(in srgb, #F0F0F0 50%, transparent)",
	bgSubdued: "#9E9E9E",
	borderDestructive: "#F13636",
	borderDivider: "color-mix(in srgb, #0B0B0B 8%, transparent)",
	borderInverse: "color-mix(in srgb, #ffffff 10%, transparent)",
	borderPrimary: "color-mix(in srgb, #0B0B0B 15%, transparent)",
	borderSecondary: "color-mix(in srgb, #0B0B0B 10%, transparent)",
	borderSolid: "#0B0B0B",
	borderSubdued: "color-mix(in srgb, #0B0B0B 5%, transparent)",
	buttonBgDestructive: "#C91313",
	buttonBgDestructiveHover: "#A40E0E",
	buttonBgDisabled: "#F7F7F7",
	buttonBgGhostHover: "#F7F7F7",
	buttonBgOutlineHover: "#F0F0F0",
	buttonBgPrimary: "#171717",
	buttonBgPrimaryHover: "#242424",
	buttonBgSecondary: "#F7F7F7",
	buttonBgSecondaryHover: "#F0F0F0",
	buttonBgSecondaryStrong: "#E7E7E7",
	buttonBgSecondaryStrongHover: "#CFCFCF",
	chartUnallocatedFill: "#F7F7F7",
	chartUnusedFill: "#E7E7E7",
	container: "#ffffff",
	containerHover: "#F7F7F7",
	containerInset: "#F7F7F7",
	containerInsetHover: "#F0F0F0",
	destructive: "#F13636",
	destructiveSubtle: "#FEB9B3",
	focusRing: "color-mix(in srgb, #0B0B0B 50%, transparent)",
	fontMono: "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
	fontSans: "'Geist', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
	fontWeightMedium: "500",
	fontWeightSemibold: "600",
	info: "#1570EF",
	link: "#1570EF",
	motionStrokeFill: "stroke-fill 3s 300ms forwards",
	navIndicator: "#0B0B0B",
	radiusLg: "10px",
	radiusMd: "8px",
	shadow: "color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowBorderLg: "0px 12px 16px -4px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderMd: "0px 4px 8px -2px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderSm: "0px 1px 6px 0px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderXl: "0px 20px 24px -4px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderXs: "0px 1px 2px 0px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowLg: "0px 12px 16px -4px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowMd: "0px 4px 8px -2px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowSm: "0px 1px 6px 0px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowXl: "0px 20px 24px -4px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowXs: "0px 1px 2px 0px color-mix(in srgb, #0B0B0B 6%, transparent)",
	success: "#078C52",
	surface: "#F7F7F7",
	surfaceHover: "#F0F0F0",
	surfaceInset: "#F0F0F0",
	surfaceInsetHover: "#E7E7E7",
	tabBgGroup: "#F7F7F7",
	tabItemActive: "#ffffff",
	tabItemHover: "#E7E7E7",
	tertiary: "color-mix(in srgb, #0B0B0B 8%, transparent)",
	textDestructiveStrong: "#C91313",
	textInfoStrong: "#175CD3",
	textInverse: "#ffffff",
	textPrimary: "#171717",
	textSecondary: "#737373",
	textSecondaryStrong: "#5C5C5C",
	textSubdued: "#9E9E9E",
	textSuccessStrong: "#05603A",
	textWarningStrong: "#B54708",
	toggleTrack: "#CFCFCF",
	warning: "#DC6803",
});

// Dark theme (for [data-theme="dark"] + the system-default path in theme.ts).
export const sureDarkTheme = stylex.createTheme(vars, {
	bgInverse: "#ffffff",
	bgInverseHover: "#F0F0F0",
	bgLoader: "#242424",
	bgOverlay: "color-mix(in srgb, #0B0B0B 85%, transparent)",
	bgSubdued: "#9E9E9E",
	borderDestructive: "#ED4E4E",
	borderDivider: "color-mix(in srgb, #ffffff 10%, transparent)",
	borderInverse: "color-mix(in srgb, #0B0B0B 15%, transparent)",
	borderPrimary: "color-mix(in srgb, #ffffff 30%, transparent)",
	borderSecondary: "color-mix(in srgb, #ffffff 20%, transparent)",
	borderSolid: "#ffffff",
	borderSubdued: "color-mix(in srgb, #ffffff 10%, transparent)",
	buttonBgDestructive: "#ED4E4E",
	buttonBgDestructiveHover: "#F13636",
	buttonBgDisabled: "#363636",
	buttonBgGhostHover: "#242424",
	buttonBgOutlineHover: "#363636",
	buttonBgPrimary: "#ffffff",
	buttonBgPrimaryHover: "#F7F7F7",
	buttonBgSecondary: "#363636",
	buttonBgSecondaryHover: "#5C5C5C",
	buttonBgSecondaryStrong: "#363636",
	buttonBgSecondaryStrongHover: "#5C5C5C",
	chartUnallocatedFill: "#363636",
	chartUnusedFill: "#737373",
	container: "#171717",
	containerHover: "#242424",
	containerInset: "#242424",
	containerInsetHover: "#363636",
	destructive: "#ED4E4E",
	destructiveSubtle: "#A40E0E",
	focusRing: "color-mix(in srgb, #ffffff 50%, transparent)",
	fontMono: "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
	fontSans: "'Geist', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
	fontWeightMedium: "500",
	fontWeightSemibold: "600",
	info: "#2E90FA",
	link: "#2E90FA",
	motionStrokeFill: "stroke-fill 3s 300ms forwards",
	navIndicator: "#ffffff",
	radiusLg: "10px",
	radiusMd: "8px",
	shadow: "color-mix(in srgb, #ffffff 8%, transparent)",
	shadowBorderLg: "0px 12px 16px -4px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderMd: "0px 4px 8px -2px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderSm: "0px 1px 6px 0px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderXl: "0px 20px 24px -4px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderXs: "0px 1px 2px 0px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowLg: "0px 12px 16px -4px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowMd: "0px 4px 8px -2px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowSm: "0px 1px 6px 0px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowXl: "0px 20px 24px -4px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowXs: "0px 1px 2px 0px color-mix(in srgb, #ffffff 8%, transparent)",
	success: "#32D583",
	surface: "#0B0B0B",
	surfaceHover: "#242424",
	surfaceInset: "#242424",
	surfaceInsetHover: "#242424",
	tabBgGroup: "color-mix(in srgb, #0B0B0B 50%, transparent)",
	tabItemActive: "#363636",
	tabItemHover: "#242424",
	tertiary: "color-mix(in srgb, #ffffff 10%, transparent)",
	textDestructiveStrong: "#F88C86",
	textInfoStrong: "#84CAFF",
	textInverse: "#171717",
	textPrimary: "#ffffff",
	textSecondary: "#CFCFCF",
	textSecondaryStrong: "#CFCFCF",
	textSubdued: "#9E9E9E",
	textSuccessStrong: "#6CE9A6",
	textWarningStrong: "#FEC84B",
	toggleTrack: "#363636",
	warning: "#FDB022",
});
