// GENERATED — do not edit by hand.
// Source: design/tokens/sure.tokens.json
// Build:  npm run tokens:build
//
// Plain-data twin of sure-tokens.stylex.ts for compiler-free consumers
// (tests, canvas/SVG charts). Values MUST match the StyleX file; the drift
// test enforces this. Never hand-edit.
import type { SureTokenName } from "./sure-tokens.stylex";

export const lightValues: Record<SureTokenName, string> = {
	bgInverse: "#242424",
	bgInverseHover: "#363636",
	bgLoader: "#F0F0F0",
	bgOverlay: "color-mix(in srgb, #F0F0F0 50%, transparent)",
	bgSubdued: "#9E9E9E",
	borderDestructive: "#F13636",
	borderDivider: "color-mix(in srgb, #0B0B0B 8%, transparent)",
	borderInverse: "color-mix(in srgb, #ffffff 10%, transparent)",
	borderPrimary: "color-mix(in srgb, #0B0B0B 15%, transparent)",
	borderSecondary: "color-mix(in srgb, #0B0B0B 10%, transparent)",
	borderSolid: "#0B0B0B",
	borderSubdued: "color-mix(in srgb, #0B0B0B 5%, transparent)",
	buttonBgDestructive: "#C91313",
	buttonBgDestructiveHover: "#A40E0E",
	buttonBgDisabled: "#F7F7F7",
	buttonBgGhostHover: "#F7F7F7",
	buttonBgOutlineHover: "#F0F0F0",
	buttonBgPrimary: "#171717",
	buttonBgPrimaryHover: "#242424",
	buttonBgSecondary: "#F7F7F7",
	buttonBgSecondaryHover: "#F0F0F0",
	buttonBgSecondaryStrong: "#E7E7E7",
	buttonBgSecondaryStrongHover: "#CFCFCF",
	chartUnallocatedFill: "#F7F7F7",
	chartUnusedFill: "#E7E7E7",
	container: "#ffffff",
	containerHover: "#F7F7F7",
	containerInset: "#F7F7F7",
	containerInsetHover: "#F0F0F0",
	destructive: "#F13636",
	destructiveSubtle: "#FEB9B3",
	focusRing: "color-mix(in srgb, #0B0B0B 50%, transparent)",
	fontMono: "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
	fontSans: "'Geist', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
	fontWeightMedium: "500",
	fontWeightSemibold: "600",
	info: "#1570EF",
	link: "#1570EF",
	motionStrokeFill: "stroke-fill 3s 300ms forwards",
	navIndicator: "#0B0B0B",
	radiusLg: "10px",
	radiusMd: "8px",
	shadow: "color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowBorderLg: "0px 12px 16px -4px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderMd: "0px 4px 8px -2px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderSm: "0px 1px 6px 0px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderXl: "0px 20px 24px -4px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowBorderXs: "0px 1px 2px 0px color-mix(in srgb, #0B0B0B 6%, transparent), 0px 0px 0px 1px color-mix(in srgb, #0B0B0B 5%, transparent)",
	shadowLg: "0px 12px 16px -4px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowMd: "0px 4px 8px -2px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowSm: "0px 1px 6px 0px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowXl: "0px 20px 24px -4px color-mix(in srgb, #0B0B0B 6%, transparent)",
	shadowXs: "0px 1px 2px 0px color-mix(in srgb, #0B0B0B 6%, transparent)",
	success: "#078C52",
	surface: "#F7F7F7",
	surfaceHover: "#F0F0F0",
	surfaceInset: "#F0F0F0",
	surfaceInsetHover: "#E7E7E7",
	tabBgGroup: "#F7F7F7",
	tabItemActive: "#ffffff",
	tabItemHover: "#E7E7E7",
	tertiary: "color-mix(in srgb, #0B0B0B 8%, transparent)",
	textDestructiveStrong: "#C91313",
	textInfoStrong: "#175CD3",
	textInverse: "#ffffff",
	textPrimary: "#171717",
	textSecondary: "#737373",
	textSecondaryStrong: "#5C5C5C",
	textSubdued: "#9E9E9E",
	textSuccessStrong: "#05603A",
	textWarningStrong: "#B54708",
	toggleTrack: "#CFCFCF",
	warning: "#DC6803",
};

export const darkValues: Record<SureTokenName, string> = {
	bgInverse: "#ffffff",
	bgInverseHover: "#F0F0F0",
	bgLoader: "#242424",
	bgOverlay: "color-mix(in srgb, #0B0B0B 85%, transparent)",
	bgSubdued: "#9E9E9E",
	borderDestructive: "#ED4E4E",
	borderDivider: "color-mix(in srgb, #ffffff 10%, transparent)",
	borderInverse: "color-mix(in srgb, #0B0B0B 15%, transparent)",
	borderPrimary: "color-mix(in srgb, #ffffff 30%, transparent)",
	borderSecondary: "color-mix(in srgb, #ffffff 20%, transparent)",
	borderSolid: "#ffffff",
	borderSubdued: "color-mix(in srgb, #ffffff 10%, transparent)",
	buttonBgDestructive: "#ED4E4E",
	buttonBgDestructiveHover: "#F13636",
	buttonBgDisabled: "#363636",
	buttonBgGhostHover: "#242424",
	buttonBgOutlineHover: "#363636",
	buttonBgPrimary: "#ffffff",
	buttonBgPrimaryHover: "#F7F7F7",
	buttonBgSecondary: "#363636",
	buttonBgSecondaryHover: "#5C5C5C",
	buttonBgSecondaryStrong: "#363636",
	buttonBgSecondaryStrongHover: "#5C5C5C",
	chartUnallocatedFill: "#363636",
	chartUnusedFill: "#737373",
	container: "#171717",
	containerHover: "#242424",
	containerInset: "#242424",
	containerInsetHover: "#363636",
	destructive: "#ED4E4E",
	destructiveSubtle: "#A40E0E",
	focusRing: "color-mix(in srgb, #ffffff 50%, transparent)",
	fontMono: "'Geist Mono', ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
	fontSans: "'Geist', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
	fontWeightMedium: "500",
	fontWeightSemibold: "600",
	info: "#2E90FA",
	link: "#2E90FA",
	motionStrokeFill: "stroke-fill 3s 300ms forwards",
	navIndicator: "#ffffff",
	radiusLg: "10px",
	radiusMd: "8px",
	shadow: "color-mix(in srgb, #ffffff 8%, transparent)",
	shadowBorderLg: "0px 12px 16px -4px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderMd: "0px 4px 8px -2px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderSm: "0px 1px 6px 0px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderXl: "0px 20px 24px -4px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowBorderXs: "0px 1px 2px 0px color-mix(in srgb, #ffffff 8%, transparent), 0px 0px 0px 1px color-mix(in srgb, #ffffff 5%, transparent)",
	shadowLg: "0px 12px 16px -4px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowMd: "0px 4px 8px -2px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowSm: "0px 1px 6px 0px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowXl: "0px 20px 24px -4px color-mix(in srgb, #ffffff 8%, transparent)",
	shadowXs: "0px 1px 2px 0px color-mix(in srgb, #ffffff 8%, transparent)",
	success: "#32D583",
	surface: "#0B0B0B",
	surfaceHover: "#242424",
	surfaceInset: "#242424",
	surfaceInsetHover: "#242424",
	tabBgGroup: "color-mix(in srgb, #0B0B0B 50%, transparent)",
	tabItemActive: "#363636",
	tabItemHover: "#242424",
	tertiary: "color-mix(in srgb, #ffffff 10%, transparent)",
	textDestructiveStrong: "#F88C86",
	textInfoStrong: "#84CAFF",
	textInverse: "#171717",
	textPrimary: "#ffffff",
	textSecondary: "#CFCFCF",
	textSecondaryStrong: "#CFCFCF",
	textSubdued: "#9E9E9E",
	textSuccessStrong: "#6CE9A6",
	textWarningStrong: "#FEC84B",
	toggleTrack: "#363636",
	warning: "#FDB022",
};

export type SureTokenGroup =
  | "color"
  | "utility"
  | "chart"
  | "typography"
  | "radius"
  | "shadow"
  | "motion";

export interface SureTokenMeta {
  readonly source: string;
  readonly group: SureTokenGroup;
}

export const tokenMeta: Record<SureTokenName, SureTokenMeta> = {
	bgInverse: { source: "utility.bg-inverse", group: "utility" },
	bgInverseHover: { source: "utility.bg-inverse-hover", group: "utility" },
	bgLoader: { source: "utility.bg-loader", group: "utility" },
	bgOverlay: { source: "utility.bg-overlay", group: "utility" },
	bgSubdued: { source: "utility.bg-subdued", group: "utility" },
	borderDestructive: { source: "utility.border-destructive", group: "utility" },
	borderDivider: { source: "utility.border-divider", group: "utility" },
	borderInverse: { source: "utility.border-inverse", group: "utility" },
	borderPrimary: { source: "utility.border-primary", group: "utility" },
	borderSecondary: { source: "utility.border-secondary", group: "utility" },
	borderSolid: { source: "utility.border-solid", group: "utility" },
	borderSubdued: { source: "utility.border-subdued", group: "utility" },
	buttonBgDestructive: { source: "utility.button-bg-destructive", group: "utility" },
	buttonBgDestructiveHover: { source: "utility.button-bg-destructive-hover", group: "utility" },
	buttonBgDisabled: { source: "utility.button-bg-disabled", group: "utility" },
	buttonBgGhostHover: { source: "utility.button-bg-ghost-hover", group: "utility" },
	buttonBgOutlineHover: { source: "utility.button-bg-outline-hover", group: "utility" },
	buttonBgPrimary: { source: "utility.button-bg-primary", group: "utility" },
	buttonBgPrimaryHover: { source: "utility.button-bg-primary-hover", group: "utility" },
	buttonBgSecondary: { source: "utility.button-bg-secondary", group: "utility" },
	buttonBgSecondaryHover: { source: "utility.button-bg-secondary-hover", group: "utility" },
	buttonBgSecondaryStrong: { source: "utility.button-bg-secondary-strong", group: "utility" },
	buttonBgSecondaryStrongHover: { source: "utility.button-bg-secondary-strong-hover", group: "utility" },
	chartUnallocatedFill: { source: "budget.unallocated-fill", group: "chart" },
	chartUnusedFill: { source: "budget.unused-fill", group: "chart" },
	container: { source: "color.container", group: "color" },
	containerHover: { source: "color.container-hover", group: "color" },
	containerInset: { source: "color.container-inset", group: "color" },
	containerInsetHover: { source: "color.container-inset-hover", group: "color" },
	destructive: { source: "color.destructive", group: "color" },
	destructiveSubtle: { source: "color.destructive-subtle", group: "color" },
	focusRing: { source: "color.focus-ring", group: "color" },
	fontMono: { source: "font.mono", group: "typography" },
	fontSans: { source: "font.sans", group: "typography" },
	fontWeightMedium: { source: "font.weight.medium", group: "typography" },
	fontWeightSemibold: { source: "font.weight.semibold", group: "typography" },
	info: { source: "color.info", group: "color" },
	link: { source: "color.link", group: "color" },
	motionStrokeFill: { source: "animate.stroke-fill", group: "motion" },
	navIndicator: { source: "color.nav-indicator", group: "color" },
	radiusLg: { source: "border.radius.lg", group: "radius" },
	radiusMd: { source: "border.radius.md", group: "radius" },
	shadow: { source: "color.shadow", group: "color" },
	shadowBorderLg: { source: "utility.shadow-border-lg", group: "utility" },
	shadowBorderMd: { source: "utility.shadow-border-md", group: "utility" },
	shadowBorderSm: { source: "utility.shadow-border-sm", group: "utility" },
	shadowBorderXl: { source: "utility.shadow-border-xl", group: "utility" },
	shadowBorderXs: { source: "utility.shadow-border-xs", group: "utility" },
	shadowLg: { source: "shadow.lg", group: "shadow" },
	shadowMd: { source: "shadow.md", group: "shadow" },
	shadowSm: { source: "shadow.sm", group: "shadow" },
	shadowXl: { source: "shadow.xl", group: "shadow" },
	shadowXs: { source: "shadow.xs", group: "shadow" },
	success: { source: "color.success", group: "color" },
	surface: { source: "color.surface", group: "color" },
	surfaceHover: { source: "color.surface-hover", group: "color" },
	surfaceInset: { source: "color.surface-inset", group: "color" },
	surfaceInsetHover: { source: "color.surface-inset-hover", group: "color" },
	tabBgGroup: { source: "utility.tab-bg-group", group: "utility" },
	tabItemActive: { source: "utility.tab-item-active", group: "utility" },
	tabItemHover: { source: "utility.tab-item-hover", group: "utility" },
	tertiary: { source: "color.tertiary", group: "color" },
	textDestructiveStrong: { source: "utility.text-destructive-strong", group: "utility" },
	textInfoStrong: { source: "utility.text-info-strong", group: "utility" },
	textInverse: { source: "utility.text-inverse", group: "utility" },
	textPrimary: { source: "utility.text-primary", group: "utility" },
	textSecondary: { source: "utility.text-secondary", group: "utility" },
	textSecondaryStrong: { source: "utility.text-secondary-strong", group: "utility" },
	textSubdued: { source: "utility.text-subdued", group: "utility" },
	textSuccessStrong: { source: "utility.text-success-strong", group: "utility" },
	textWarningStrong: { source: "utility.text-warning-strong", group: "utility" },
	toggleTrack: { source: "color.toggle-track", group: "color" },
	warning: { source: "color.warning", group: "color" },
};
