/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import { ErrorResponse, PushSubscription } from "../../models";

/**
 * @summary Register an APNs device token
 */
export const PostApiV1PushSubscriptionsBody = zod.strictObject({
	token: zod.string(),
	environment: zod.enum(["sandbox", "production"]),
	platform: zod.enum(["ios"]),
});

export const PostApiV1PushSubscriptions201Response = PushSubscription;

export const PostApiV1PushSubscriptions422Response = ErrorResponse;

/**
 * @summary Unregister an APNs device token
 */
export const DeleteApiV1PushSubscriptionsIdParams = zod.strictObject({
	id: zod.string(),
});

export const DeleteApiV1PushSubscriptionsId204Response = zod.void();
