/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import { ApiMetadata, ErrorResponse } from "../../models";

/**
 * Public contract version and capability tokens for the alternate frontend compatibility check (readiness and session establishment). No authentication required.
 * @summary Retrieve API contract metadata
 */
export const GetApiV1MetadataHeader = zod.strictObject({
	"X-Api-Key": zod
		.string()
		.exactOptional()
		.describe(
			"Optional deployment API key. Absence keeps the endpoint public; a presented key that is unknown or inactive returns 401.",
		),
});

export const GetApiV1Metadata200Response = ApiMetadata;

export const GetApiV1Metadata401Response = ErrorResponse;
