/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import { ErrorResponse, TransferDecision, TransferDecisionCollection } from "../../models";

/**
 * @summary List transfers
 */
export const GetApiV1TransfersQueryParams = zod.strictObject({
	page: zod.int().exactOptional().describe("Page number (default: 1)"),
	per_page: zod.int().exactOptional().describe("Items per page (default: 25, max: 100)"),
	status: zod.enum(["pending", "confirmed"]).exactOptional().describe("Filter by transfer status"),
	account_id: zod.uuid().exactOptional().describe("Filter transfers involving this account"),
	start_date: zod.iso.date().exactOptional().describe("Filter transfers from this date"),
	end_date: zod.iso.date().exactOptional().describe("Filter transfers until this date"),
});

export const GetApiV1Transfers200Response = TransferDecisionCollection;

export const GetApiV1Transfers401Response = ErrorResponse;

export const GetApiV1Transfers403Response = ErrorResponse;

export const GetApiV1Transfers422Response = ErrorResponse;

/**
 * @summary Retrieve a transfer
 */
export const GetApiV1TransfersIdParams = zod.strictObject({
	id: zod.string().describe("Transfer ID"),
});

export const GetApiV1TransfersId200Response = TransferDecision;

export const GetApiV1TransfersId401Response = ErrorResponse;

export const GetApiV1TransfersId403Response = ErrorResponse;

export const GetApiV1TransfersId404Response = ErrorResponse;
