/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

import {
  ErrorResponse,
  TransferDecision,
  TransferDecisionCollection
} from '../../models';


/**
 * @summary List transfers
 */
export const GetApiV1TransfersQueryParams = zod.object({
  "page": zod.int().optional().describe('Page number (default: 1)'),
  "per_page": zod.int().optional().describe('Items per page (default: 25, max: 100)'),
  "status": zod.enum(['pending', 'confirmed']).optional().describe('Filter by transfer status'),
  "account_id": zod.uuid().optional().describe('Filter transfers involving this account'),
  "start_date": zod.iso.date().optional().describe('Filter transfers from this date'),
  "end_date": zod.iso.date().optional().describe('Filter transfers until this date')
})

export const GetApiV1Transfers200Response = TransferDecisionCollection

export const GetApiV1Transfers401Response = ErrorResponse

export const GetApiV1Transfers403Response = ErrorResponse

export const GetApiV1Transfers422Response = ErrorResponse

/**
 * @summary Retrieve a transfer
 */
export const GetApiV1TransfersIdParams = zod.object({
  "id": zod.string().describe('Transfer ID')
})

export const GetApiV1TransfersId200Response = TransferDecision

export const GetApiV1TransfersId401Response = ErrorResponse

export const GetApiV1TransfersId403Response = ErrorResponse

export const GetApiV1TransfersId404Response = ErrorResponse

