/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';

import {
  ErrorResponse,
  ErrorResponseWithImportId,
  ImportCollection,
  ImportPreflightResponse,
  ImportResponse,
  ImportRowDiagnosticCollection
} from '../../models';


/**
 * List all imports for the user's family with pagination and filtering.
 * @summary List imports
 */
export const GetApiV1ImportsQueryParams = zod.object({
  "page": zod.int().optional().describe('Page number (default: 1)'),
  "per_page": zod.int().optional().describe('Items per page (default: 25, max: 100)'),
  "status": zod.enum(['pending', 'complete', 'importing', 'reverting', 'revert_failed', 'failed']).optional().describe('Filter by status'),
  "type": zod.enum(['TransactionImport', 'TradeImport', 'AccountImport', 'MintImport', 'ActualImport', 'YnabImport', 'CategoryImport', 'RuleImport', 'MerchantImport', 'PdfImport', 'QifImport', 'SureImport']).optional().describe('Filter by import type')
})

export const GetApiV1Imports200Response = ImportCollection

/**
 * Create a new import from raw CSV content, inline Sure NDJSON content, or an uploaded Sure NDJSON file. CSV content is limited to 10MB.
 * @summary Create import
 */
export const PostApiV1ImportsBody = zod.object({
  "raw_file_content": zod.string().optional().describe('Raw CSV or Sure NDJSON content as a string. CSV content is limited to 10MB. Required for SureImport unless a multipart file is uploaded.'),
  "type": zod.enum(['TransactionImport', 'TradeImport', 'AccountImport', 'MintImport', 'ActualImport', 'YnabImport', 'CategoryImport', 'RuleImport', 'MerchantImport', 'PdfImport', 'QifImport', 'SureImport']).optional().describe('Import type (defaults to TransactionImport)'),
  "account_id": zod.uuid().optional().describe('Account ID to import into'),
  "publish": zod.string().optional().describe('Set to "true" to automatically queue for processing if configuration is valid'),
  "date_col_label": zod.string().optional().describe('CSV imports only. Header name for the date column'),
  "amount_col_label": zod.string().optional().describe('CSV imports only. Header name for the amount column'),
  "name_col_label": zod.string().optional().describe('CSV imports only. Header name for the transaction name column'),
  "category_col_label": zod.string().optional().describe('CSV imports only. Header name for the category column'),
  "tags_col_label": zod.string().optional().describe('CSV imports only. Header name for the tags column'),
  "notes_col_label": zod.string().optional().describe('CSV imports only. Header name for the notes column'),
  "account_col_label": zod.string().optional().describe('CSV imports only. Header name for the account column when importing rows across multiple accounts'),
  "qty_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the quantity column'),
  "ticker_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the ticker column'),
  "price_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the price column'),
  "entity_type_col_label": zod.string().optional().describe('CSV imports only. Header name for the entity type column'),
  "currency_col_label": zod.string().optional().describe('CSV imports only. Header name for the currency column'),
  "exchange_operating_mic_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the exchange operating MIC column'),
  "date_format": zod.string().optional().describe('CSV imports only. Date format pattern (e.g., "%m/%d/%Y")'),
  "number_format": zod.enum(['1,234.56', '1.234,56', '1 234,56', '1,234']).optional().describe('CSV imports only. Number format for parsing amounts'),
  "signage_convention": zod.enum(['inflows_positive', 'inflows_negative']).optional().describe('CSV imports only. How to interpret positive/negative amounts'),
  "col_sep": zod.enum([',', ';']).optional().describe('CSV imports only. Column separator'),
  "amount_type_strategy": zod.enum(['signed_amount', 'custom_column']).optional().describe('CSV imports only. Amount parsing strategy'),
  "amount_type_inflow_value": zod.string().optional().describe('CSV imports only. Column value that marks an amount as an inflow when using custom_column strategy')
})

export const PostApiV1Imports201Response = ImportResponse

export const PostApiV1Imports422Response = zod.union([ErrorResponse,ErrorResponseWithImportId])

export const PostApiV1Imports500Response = ErrorResponseWithImportId

/**
 * Retrieve detailed information about a specific import, including configuration, row statistics, and SureImport readback verification when available.
 * @summary Retrieve an import
 */
export const GetApiV1ImportsIdParams = zod.object({
  "id": zod.string().describe('Import ID')
})

export const GetApiV1ImportsId200Response = ImportResponse

export const GetApiV1ImportsId404Response = ErrorResponse

/**
 * List sanitized import rows with validation errors and mapping resolution state.
 * @summary List import row diagnostics
 */
export const GetApiV1ImportsIdRowsParams = zod.object({
  "id": zod.string().describe('Import ID')
})

export const GetApiV1ImportsIdRowsQueryParams = zod.object({
  "page": zod.int().optional().describe('Page number (default: 1)'),
  "per_page": zod.int().optional().describe('Items per page (default: 25, max: 100)')
})

export const GetApiV1ImportsIdRows200Response = ImportRowDiagnosticCollection

export const GetApiV1ImportsIdRows401Response = ErrorResponse

export const GetApiV1ImportsIdRows403Response = ErrorResponse

export const GetApiV1ImportsIdRows404Response = ErrorResponse

export const GetApiV1ImportsIdRows500Response = ErrorResponse

/**
 * Validate CSV or Sure NDJSON import content and return counts, headers, warnings, and validation errors without persisting an import or enqueueing jobs. CSV content is limited to 10MB.
 * @summary Validate import content without creating an import
 */
export const postApiV1ImportsPreflightBodyRowsToSkipMin = 0;



export const PostApiV1ImportsPreflightBody = zod.object({
  "raw_file_content": zod.string().optional().describe('Raw CSV or Sure NDJSON content as a string. CSV content is limited to 10MB.'),
  "file": zod.instanceof(Blob).optional().describe('CSV or Sure NDJSON upload when using multipart/form-data. CSV files are limited to 10MB.'),
  "type": zod.enum(['TransactionImport', 'TradeImport', 'AccountImport', 'MintImport', 'ActualImport', 'YnabImport', 'CategoryImport', 'RuleImport', 'MerchantImport', 'PdfImport', 'QifImport', 'SureImport']).optional().describe('Import type to validate (defaults to TransactionImport)'),
  "account_id": zod.uuid().optional().describe('Account ID used for account-scoped CSV import validation'),
  "date_col_label": zod.string().optional().describe('CSV imports only. Header name for the date column'),
  "amount_col_label": zod.string().optional().describe('CSV imports only. Header name for the amount column'),
  "name_col_label": zod.string().optional().describe('CSV imports only. Header name for the transaction name column'),
  "category_col_label": zod.string().optional().describe('CSV imports only. Header name for the category column'),
  "tags_col_label": zod.string().optional().describe('CSV imports only. Header name for the tags column'),
  "notes_col_label": zod.string().optional().describe('CSV imports only. Header name for the notes column'),
  "account_col_label": zod.string().optional().describe('CSV imports only. Header name for the account column'),
  "qty_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the quantity column'),
  "ticker_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the ticker column'),
  "price_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the price column'),
  "entity_type_col_label": zod.string().optional().describe('CSV imports only. Header name for the entity type column'),
  "currency_col_label": zod.string().optional().describe('CSV imports only. Header name for the currency column'),
  "exchange_operating_mic_col_label": zod.string().optional().describe('CSV trade imports only. Header name for the exchange operating MIC column'),
  "date_format": zod.string().optional().describe('CSV imports only. Date format pattern'),
  "number_format": zod.enum(['1,234.56', '1.234,56', '1 234,56', '1,234']).optional().describe('CSV imports only. Number format for parsing amounts'),
  "signage_convention": zod.enum(['inflows_positive', 'inflows_negative']).optional().describe('CSV imports only. How to interpret positive/negative amounts'),
  "col_sep": zod.enum([',', ';']).optional().describe('CSV imports only. Column separator'),
  "rows_to_skip": zod.int().min(postApiV1ImportsPreflightBodyRowsToSkipMin).optional().describe('CSV imports only. Number of leading rows to skip before reading headers'),
  "amount_type_strategy": zod.enum(['signed_amount', 'custom_column']).optional().describe('CSV imports only. Amount parsing strategy'),
  "amount_type_inflow_value": zod.string().optional().describe('CSV imports only. Column value that marks an amount as an inflow when using custom_column strategy')
})

export const PostApiV1ImportsPreflight200Response = ImportPreflightResponse

export const PostApiV1ImportsPreflight401Response = ErrorResponse

export const PostApiV1ImportsPreflight404Response = ErrorResponse

export const PostApiV1ImportsPreflight422Response = ErrorResponse

