/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sure API
 * OpenAPI documentation generated from executable request specs.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

import { ErrorResponse, Holding, HoldingCollection } from "../../models";

/**
 * @summary List holdings
 */
export const GetApiV1HoldingsQueryParams = zod.strictObject({
	page: zod.int().exactOptional().describe("Page number (default: 1)"),
	per_page: zod.int().exactOptional().describe("Items per page (default: 25, max: 100)"),
	account_id: zod.string().exactOptional().describe("Filter by account ID"),
	account_ids: zod.array(zod.string()).exactOptional().describe("Filter by multiple account IDs"),
	date: zod.iso.date().exactOptional().describe("Filter by exact date"),
	start_date: zod.iso.date().exactOptional().describe("Filter holdings from this date (inclusive)"),
	end_date: zod.iso.date().exactOptional().describe("Filter holdings until this date (inclusive)"),
	security_id: zod.string().exactOptional().describe("Filter by security ID"),
});

export const GetApiV1Holdings200Response = HoldingCollection;

export const GetApiV1Holdings401Response = ErrorResponse;

export const GetApiV1Holdings422Response = ErrorResponse;

/**
 * @summary Retrieve holding
 */
export const GetApiV1HoldingsIdParams = zod.strictObject({
	id: zod.string().describe("Holding ID"),
});

export const GetApiV1HoldingsId200Response = Holding;

export const GetApiV1HoldingsId401Response = ErrorResponse;

export const GetApiV1HoldingsId404Response = ErrorResponse;
